export type Sticker = {
    id: string;
    emoji: string;
    label: { ko: string; en: string };
};

export const STICKERS: Sticker[] = [
    { id: 'love', emoji: '😍', label: { ko: '사랑', en: 'Love' } },
    { id: 'heart', emoji: '❤️', label: { ko: '하트', en: 'Heart' } },
    { id: 'hearts', emoji: '💕', label: { ko: '하트들', en: 'Hearts' } },
    { id: 'sparkheart', emoji: '💖', label: { ko: '반짝하트', en: 'Sparkle heart' } },
    { id: 'twohearts', emoji: '💗', label: { ko: '두하트', en: 'Growing heart' } },
    { id: 'revheart', emoji: '💞', label: { ko: '도는하트', en: 'Revolving' } },
    { id: 'beatheart', emoji: '💓', label: { ko: '두근', en: 'Beating' } },
    { id: 'brokenheart', emoji: '💔', label: { ko: '상심', en: 'Broken' } },
    { id: 'blackheart', emoji: '🖤', label: { ko: '검은하트', en: 'Black heart' } },
    { id: 'whiteheart', emoji: '🤍', label: { ko: '흰하트', en: 'White heart' } },
    { id: 'orangeheart', emoji: '🧡', label: { ko: '주황하트', en: 'Orange heart' } },
    { id: 'yellowheart', emoji: '💛', label: { ko: '노란하트', en: 'Yellow heart' } },
    { id: 'greenheart', emoji: '💚', label: { ko: '초록하트', en: 'Green heart' } },
    { id: 'blueheart', emoji: '💙', label: { ko: '파란하트', en: 'Blue heart' } },
    { id: 'purpleheart', emoji: '💜', label: { ko: '보라하트', en: 'Purple heart' } },
    { id: 'brownheart', emoji: '🤎', label: { ko: '갈색하트', en: 'Brown heart' } },
    { id: 'kiss', emoji: '😘', label: { ko: '뽀뽀', en: 'Kiss' } },
    { id: 'kissface', emoji: '😗', label: { ko: '키스', en: 'Kissing' } },
    { id: 'kisswink', emoji: '😙', label: { ko: '윙키스', en: 'Kiss smile' } },
    { id: 'kissclosed', emoji: '😚', label: { ko: '눈감키스', en: 'Kiss closed' } },
    { id: 'blush', emoji: '☺️', label: { ko: '수줍', en: 'Blush' } },
    { id: 'like', emoji: '👍', label: { ko: '좋아요', en: 'Like' } },
    { id: 'dislike', emoji: '👎', label: { ko: '싫어요', en: 'Dislike' } },
    { id: 'ok', emoji: '😊', label: { ko: '미소', en: 'Smile' } },
    { id: 'slight', emoji: '🙂', label: { ko: '살짝', en: 'Slight' } },
    { id: 'upside', emoji: '🙃', label: { ko: '뒤집힌', en: 'Upside down' } },
    { id: 'grin', emoji: '😁', label: { ko: '활짝', en: 'Grin' } },
    { id: 'beaming', emoji: '😄', label: { ko: '방긋', en: 'Beaming' } },
    { id: 'smile', emoji: '😃', label: { ko: '웃음', en: 'Smile' } },
    { id: 'lol', emoji: '😂', label: { ko: '웃겨', en: 'LOL' } },
    { id: 'rofl', emoji: '🤣', label: { ko: '폭소', en: 'ROFL' } },
    { id: 'joy', emoji: '😆', label: { ko: '깔깔', en: 'Joy' } },
    { id: 'wink', emoji: '😉', label: { ko: '윙크', en: 'Wink' } },
    { id: 'cool', emoji: '😎', label: { ko: '멋짐', en: 'Cool' } },
    { id: 'nerd', emoji: '🤓', label: { ko: '똑똑', en: 'Nerd' } },
    { id: 'think', emoji: '🤔', label: { ko: '생각', en: 'Think' } },
    { id: 'hmm', emoji: '🧐', label: { ko: '관찰', en: 'Hmm' } },
    { id: 'wow', emoji: '😮', label: { ko: '놀람', en: 'Wow' } },
    { id: 'open', emoji: '😯', label: { ko: '헉', en: 'Gasp' } },
    { id: 'scream', emoji: '😱', label: { ko: '충격', en: 'Shock' } },
    { id: 'fear', emoji: '😨', label: { ko: '무서워', en: 'Fear' } },
    { id: 'anxious', emoji: '😰', label: { ko: '불안', en: 'Anxious' } },
    { id: 'cold', emoji: '🥶', label: { ko: '추워', en: 'Cold' } },
    { id: 'hot', emoji: '🥵', label: { ko: '더워', en: 'Hot' } },
    { id: 'sad', emoji: '😢', label: { ko: '슬픔', en: 'Sad' } },
    { id: 'cry', emoji: '😭', label: { ko: '울음', en: 'Cry' } },
    { id: 'sweat', emoji: '😅', label: { ko: '식은땀', en: 'Sweat' } },
    { id: 'tired', emoji: '😫', label: { ko: '지쳐', en: 'Tired' } },
    { id: 'weary', emoji: '😩', label: { ko: '힘듦', en: 'Weary' } },
    { id: 'pensive', emoji: '😔', label: { ko: '시무룩', en: 'Pensive' } },
    { id: 'disappointed', emoji: '😞', label: { ko: '실망', en: 'Disappointed' } },
    { id: 'worried', emoji: '😟', label: { ko: '걱정', en: 'Worried' } },
    { id: 'confound', emoji: '😖', label: { ko: '괴로움', en: 'Confounded' } },
    { id: 'persevere', emoji: '😣', label: { ko: '참음', en: 'Persevere' } },
    { id: 'angry', emoji: '😡', label: { ko: '화남', en: 'Angry' } },
    { id: 'mad', emoji: '🤬', label: { ko: '열받음', en: 'Mad' } },
    { id: 'pout', emoji: '😤', label: { ko: '흥', en: 'Humph' } },
    { id: 'sick', emoji: '🤒', label: { ko: '아픔', en: 'Sick' } },
    { id: 'mask', emoji: '😷', label: { ko: '마스크', en: 'Mask' } },
    { id: 'nauseated', emoji: '🤢', label: { ko: '메스꺼움', en: 'Nauseated' } },
    { id: 'vomit', emoji: '🤮', label: { ko: '토함', en: 'Vomit' } },
    { id: 'dizzy', emoji: '😵', label: { ko: '어지러움', en: 'Dizzy' } },
    { id: 'explode', emoji: '🤯', label: { ko: '멘붕', en: 'Mind blown' } },
    { id: 'sleepy', emoji: '😴', label: { ko: '졸림', en: 'Sleepy' } },
    { id: 'yawn', emoji: '🥱', label: { ko: '하품', en: 'Yawn' } },
    { id: 'drool', emoji: '🤤', label: { ko: '침', en: 'Drool' } },
    { id: 'zany', emoji: '😜', label: { ko: '윙메롱', en: 'Zany' } },
    { id: 'money', emoji: '🤑', label: { ko: '돈', en: 'Money' } },
    { id: 'shush', emoji: '🤫', label: { ko: '쉿', en: 'Shush' } },
    { id: 'handmouth', emoji: '🤭', label: { ko: '손으로가림', en: 'Oops' } },
    { id: 'liar', emoji: '🤥', label: { ko: '거짓말', en: 'Lie' } },
    { id: 'neutral', emoji: '😐', label: { ko: '무표정', en: 'Neutral' } },
    { id: 'expressionless', emoji: '😑', label: { ko: '담담', en: 'Blank' } },
    { id: 'unamused', emoji: '😒', label: { ko: '시큰둥', en: 'Unamused' } },
    { id: 'rolling', emoji: '🙄', label: { ko: '눈굴림', en: 'Eye roll' } },
    { id: 'grimace', emoji: '😬', label: { ko: '찌푸림', en: 'Grimace' } },
    { id: 'relieved', emoji: '😌', label: { ko: '안도', en: 'Relieved' } },
    { id: 'smirk', emoji: '😏', label: { ko: '히죽', en: 'Smirk' } },
    { id: 'sleepface', emoji: '😪', label: { ko: '비몽', en: 'Sleepy face' } },
    { id: 'thanks', emoji: '🙏', label: { ko: '감사', en: 'Thanks' } },
    { id: 'clap', emoji: '👏', label: { ko: '박수', en: 'Clap' } },
    { id: 'wave', emoji: '👋', label: { ko: '안녕', en: 'Hi' } },
    { id: 'flex', emoji: '💪', label: { ko: '힘냄', en: 'Strong' } },
    { id: 'punch', emoji: '👊', label: { ko: '주먹', en: 'Punch' } },
    { id: 'fist', emoji: '✊', label: { ko: '주먹쥐기', en: 'Fist' } },
    { id: 'leftfist', emoji: '🤛', label: { ko: '왼주먹', en: 'Left fist' } },
    { id: 'rightfist', emoji: '🤜', label: { ko: '오른주먹', en: 'Right fist' } },
    { id: 'peace', emoji: '✌️', label: { ko: '피스', en: 'Peace' } },
    { id: 'okhand', emoji: '👌', label: { ko: '오케이', en: 'OK' } },
    { id: 'fingers', emoji: '🤞', label: { ko: '행운', en: 'Luck' } },
    { id: 'loveu', emoji: '🤟', label: { ko: '사랑해손', en: 'Love you' } },
    { id: 'horns', emoji: '🤘', label: { ko: '락', en: 'Rock' } },
    { id: 'callme', emoji: '🤙', label: { ko: '전화해', en: 'Call me' } },
    { id: 'pointup', emoji: '☝️', label: { ko: '위', en: 'Up' } },
    { id: 'pointup2', emoji: '👆', label: { ko: '위쪽', en: 'Up 2' } },
    { id: 'pointdown', emoji: '👇', label: { ko: '아래', en: 'Down' } },
    { id: 'pointleft', emoji: '👈', label: { ko: '왼쪽', en: 'Left' } },
    { id: 'pointright', emoji: '👉', label: { ko: '오른쪽', en: 'Right' } },
    { id: 'palm', emoji: '✋', label: { ko: '손바닥', en: 'Palm' } },
    { id: 'raised', emoji: '🤚', label: { ko: '손등', en: 'Raised' } },
    { id: 'splay', emoji: '🖐️', label: { ko: '쫙', en: 'Splayed' } },
    { id: 'vulcan', emoji: '🖖', label: { ko: '벌칸', en: 'Vulcan' } },
    { id: 'selfie', emoji: '🤳', label: { ko: '셀카', en: 'Selfie' } },
    { id: 'nail', emoji: '💅', label: { ko: '네일', en: 'Nails' } },
    { id: 'writehand', emoji: '✍️', label: { ko: '글씨', en: 'Writing' } },
    { id: 'prayfold', emoji: '🤲', label: { ko: '모음', en: 'Palms' } },
    { id: 'handshake', emoji: '🤝', label: { ko: '악수', en: 'Handshake' } },
    { id: 'hug', emoji: '🤗', label: { ko: '포옹', en: 'Hug' } },
    { id: 'party', emoji: '🎉', label: { ko: '축하', en: 'Party' } },
    { id: 'tada', emoji: '🎊', label: { ko: '축하해', en: 'Confetti' } },
    { id: 'gift', emoji: '🎁', label: { ko: '선물', en: 'Gift' } },
    { id: 'balloon', emoji: '🎈', label: { ko: '풍선', en: 'Balloon' } },
    { id: 'ribbon', emoji: '🎀', label: { ko: '리본', en: 'Ribbon' } },
    { id: 'ticket', emoji: '🎫', label: { ko: '티켓', en: 'Ticket' } },
    { id: 'fire', emoji: '🔥', label: { ko: '대박', en: 'Fire' } },
    { id: 'best', emoji: '🏆', label: { ko: '최고', en: 'Best' } },
    { id: 'medal', emoji: '🥇', label: { ko: '1등', en: 'Gold' } },
    { id: 'silver', emoji: '🥈', label: { ko: '2등', en: 'Silver' } },
    { id: 'bronze', emoji: '🥉', label: { ko: '3등', en: 'Bronze' } },
    { id: 'star', emoji: '⭐', label: { ko: '별', en: 'Star' } },
    { id: 'glowstar', emoji: '🌟', label: { ko: '반짝별', en: 'Glow' } },
    { id: 'dizzystar', emoji: '💫', label: { ko: '어지별', en: 'Dizzy star' } },
    { id: 'hundred', emoji: '💯', label: { ko: '백점', en: '100' } },
    { id: 'sparkle', emoji: '✨', label: { ko: '반짝', en: 'Sparkle' } },
    { id: 'boom', emoji: '💥', label: { ko: '펑', en: 'Boom' } },
    { id: 'zzz', emoji: '💤', label: { ko: '쿨쿨', en: 'Zzz' } },
    { id: 'sweatdrop', emoji: '💦', label: { ko: '땀', en: 'Sweat drop' } },
    { id: 'dash', emoji: '💨', label: { ko: '질주', en: 'Dash' } },
    { id: 'check', emoji: '✅', label: { ko: '확인', en: 'Check' } },
    { id: 'cross', emoji: '❌', label: { ko: '아니', en: 'No' } },
    { id: 'question', emoji: '❓', label: { ko: '질문', en: 'Question' } },
    { id: 'bang', emoji: '❗', label: { ko: '강조', en: 'Bang' } },
    { id: 'exclaimq', emoji: '⁉️', label: { ko: '뭐야', en: 'Exclaim q' } },
    { id: 'doublebang', emoji: '‼️', label: { ko: '진짜', en: 'Double bang' } },
    { id: 'idea', emoji: '💡', label: { ko: '아이디어', en: 'Idea' } },
    { id: 'memo', emoji: '📝', label: { ko: '메모', en: 'Memo' } },
    { id: 'pin', emoji: '📌', label: { ko: '고정', en: 'Pin' } },
    { id: 'bell', emoji: '🔔', label: { ko: '알림', en: 'Bell' } },
    { id: 'megaphone', emoji: '📢', label: { ko: '확성기', en: 'Mega' } },
    { id: 'eyes', emoji: '👀', label: { ko: '관심', en: 'Eyes' } },
    { id: 'tongue', emoji: '😛', label: { ko: '메롱', en: 'Tongue' } },
    { id: 'silly', emoji: '🤪', label: { ko: '장난', en: 'Silly' } },
    { id: 'angel', emoji: '😇', label: { ko: '천사', en: 'Angel' } },
    { id: 'devil', emoji: '😈', label: { ko: '장난꾸러기', en: 'Devil' } },
    { id: 'imp', emoji: '👿', label: { ko: '삐짐', en: 'Imp' } },
    { id: 'skull', emoji: '💀', label: { ko: '해골', en: 'Skull' } },
    { id: 'poop', emoji: '💩', label: { ko: '똥', en: 'Poop' } },
    { id: 'ghost', emoji: '👻', label: { ko: '유령', en: 'Ghost' } },
    { id: 'robot', emoji: '🤖', label: { ko: '로봇', en: 'Robot' } },
    { id: 'alien', emoji: '👽', label: { ko: '외계인', en: 'Alien' } },
    { id: 'clown', emoji: '🤡', label: { ko: '광대', en: 'Clown' } },
    { id: 'ogre', emoji: '👹', label: { ko: '도깨비', en: 'Ogre' } },
    { id: 'goblin', emoji: '👺', label: { ko: '천구', en: 'Goblin' } },
    { id: 'jack', emoji: '🎃', label: { ko: '호박', en: 'Pumpkin' } },
    { id: 'cat', emoji: '🐱', label: { ko: '고양이', en: 'Cat' } },
    { id: 'catgrin', emoji: '😺', label: { ko: '고양미소', en: 'Cat grin' } },
    { id: 'catjoy', emoji: '😹', label: { ko: '고양웃음', en: 'Cat joy' } },
    { id: 'catheart', emoji: '😻', label: { ko: '고양사랑', en: 'Cat love' } },
    { id: 'catsmirk', emoji: '😼', label: { ko: '고양히죽', en: 'Cat smirk' } },
    { id: 'catkiss', emoji: '😽', label: { ko: '고양뽀뽀', en: 'Cat kiss' } },
    { id: 'catscream', emoji: '🙀', label: { ko: '고양헉', en: 'Cat scream' } },
    { id: 'catcry', emoji: '😿', label: { ko: '고양울음', en: 'Cat cry' } },
    { id: 'catpout', emoji: '😾', label: { ko: '고양삐짐', en: 'Cat pout' } },
    { id: 'dog', emoji: '🐶', label: { ko: '강아지', en: 'Dog' } },
    { id: 'bear', emoji: '🐻', label: { ko: '곰', en: 'Bear' } },
    { id: 'panda', emoji: '🐼', label: { ko: '팬더', en: 'Panda' } },
    { id: 'fox', emoji: '🦊', label: { ko: '여우', en: 'Fox' } },
    { id: 'rabbit', emoji: '🐰', label: { ko: '토끼', en: 'Rabbit' } },
    { id: 'tiger', emoji: '🐯', label: { ko: '호랑이', en: 'Tiger' } },
    { id: 'lion', emoji: '🦁', label: { ko: '사자', en: 'Lion' } },
    { id: 'cow', emoji: '🐮', label: { ko: '소', en: 'Cow' } },
    { id: 'pig', emoji: '🐷', label: { ko: '돼지', en: 'Pig' } },
    { id: 'frog', emoji: '🐸', label: { ko: '개구리', en: 'Frog' } },
    { id: 'monkey', emoji: '🐵', label: { ko: '원숭이', en: 'Monkey' } },
    { id: 'see', emoji: '🙈', label: { ko: '안보임', en: 'See no' } },
    { id: 'hear', emoji: '🙉', label: { ko: '안들림', en: 'Hear no' } },
    { id: 'speak', emoji: '🙊', label: { ko: '안말함', en: 'Speak no' } },
    { id: 'chicken', emoji: '🐔', label: { ko: '닭', en: 'Chicken' } },
    { id: 'penguin', emoji: '🐧', label: { ko: '펭귄', en: 'Penguin' } },
    { id: 'bird', emoji: '🐦', label: { ko: '새', en: 'Bird' } },
    { id: 'chick', emoji: '🐥', label: { ko: '병아리', en: 'Chick' } },
    { id: 'owl', emoji: '🦉', label: { ko: '올빼미', en: 'Owl' } },
    { id: 'unicorn', emoji: '🦄', label: { ko: '유니콘', en: 'Unicorn' } },
    { id: 'horse', emoji: '🐴', label: { ko: '말', en: 'Horse' } },
    { id: 'bee', emoji: '🐝', label: { ko: '벌', en: 'Bee' } },
    { id: 'bug', emoji: '🐛', label: { ko: '벌레', en: 'Bug' } },
    { id: 'butterfly', emoji: '🦋', label: { ko: '나비', en: 'Butterfly' } },
    { id: 'turtle', emoji: '🐢', label: { ko: '거북', en: 'Turtle' } },
    { id: 'octopus', emoji: '🐙', label: { ko: '문어', en: 'Octopus' } },
    { id: 'whale', emoji: '🐳', label: { ko: '고래', en: 'Whale' } },
    { id: 'dolphin', emoji: '🐬', label: { ko: '돌고래', en: 'Dolphin' } },
    { id: 'fish', emoji: '🐟', label: { ko: '물고기', en: 'Fish' } },
    { id: 'sun', emoji: '☀️', label: { ko: '해', en: 'Sun' } },
    { id: 'moon', emoji: '🌙', label: { ko: '달', en: 'Moon' } },
    { id: 'fullmoon', emoji: '🌕', label: { ko: '보름달', en: 'Full moon' } },
    { id: 'starstruck', emoji: '🤩', label: { ko: '반함', en: 'Starstruck' } },
    { id: 'rainbow', emoji: '🌈', label: { ko: '무지개', en: 'Rainbow' } },
    { id: 'cloud', emoji: '☁️', label: { ko: '구름', en: 'Cloud' } },
    { id: 'rain', emoji: '🌧️', label: { ko: '비', en: 'Rain' } },
    { id: 'thunder', emoji: '⛈️', label: { ko: '천둥', en: 'Storm' } },
    { id: 'lightning', emoji: '⚡', label: { ko: '번개', en: 'Zap' } },
    { id: 'snow', emoji: '❄️', label: { ko: '눈', en: 'Snow' } },
    { id: 'snowman', emoji: '⛄', label: { ko: '눈사람', en: 'Snowman' } },
    { id: 'umbrella', emoji: '☔', label: { ko: '우산', en: 'Umbrella' } },
    { id: 'flower', emoji: '🌸', label: { ko: '벚꽃', en: 'Cherry' } },
    { id: 'rose', emoji: '🌹', label: { ko: '장미', en: 'Rose' } },
    { id: 'tulip', emoji: '🌷', label: { ko: '튤립', en: 'Tulip' } },
    { id: 'sunflower', emoji: '🌻', label: { ko: '해바라기', en: 'Sunflower' } },
    { id: 'bouquet', emoji: '💐', label: { ko: '꽃다발', en: 'Bouquet' } },
    { id: 'leaf', emoji: '🍀', label: { ko: '네잎', en: 'Clover' } },
    { id: 'tree', emoji: '🌳', label: { ko: '나무', en: 'Tree' } },
    { id: 'coffee', emoji: '☕', label: { ko: '커피', en: 'Coffee' } },
    { id: 'tea', emoji: '🍵', label: { ko: '차', en: 'Tea' } },
    { id: 'bubbletea', emoji: '🧋', label: { ko: '버블티', en: 'Boba' } },
    { id: 'beer', emoji: '🍺', label: { ko: '맥주', en: 'Beer' } },
    { id: 'beers', emoji: '🍻', label: { ko: '건배', en: 'Cheers' } },
    { id: 'wine', emoji: '🍷', label: { ko: '와인', en: 'Wine' } },
    { id: 'sake', emoji: '🍶', label: { ko: '사케', en: 'Sake' } },
    { id: 'soju', emoji: '🥃', label: { ko: '소주', en: 'Soju' } },
    { id: 'cake', emoji: '🎂', label: { ko: '케이크', en: 'Cake' } },
    { id: 'shortcake', emoji: '🍰', label: { ko: '조각케익', en: 'Slice' } },
    { id: 'donut', emoji: '🍩', label: { ko: '도넛', en: 'Donut' } },
    { id: 'cookie', emoji: '🍪', label: { ko: '쿠키', en: 'Cookie' } },
    { id: 'icecream', emoji: '🍦', label: { ko: '아이스크림', en: 'Ice cream' } },
    { id: 'chocolate', emoji: '🍫', label: { ko: '초콜릿', en: 'Chocolate' } },
    { id: 'candy', emoji: '🍬', label: { ko: '사탕', en: 'Candy' } },
    { id: 'lollipop', emoji: '🍭', label: { ko: '막대사탕', en: 'Lollipop' } },
    { id: 'food', emoji: '🍔', label: { ko: '음식', en: 'Food' } },
    { id: 'pizza', emoji: '🍕', label: { ko: '피자', en: 'Pizza' } },
    { id: 'fries', emoji: '🍟', label: { ko: '감자튀김', en: 'Fries' } },
    { id: 'hotdog', emoji: '🌭', label: { ko: '핫도그', en: 'Hotdog' } },
    { id: 'taco', emoji: '🌮', label: { ko: '타코', en: 'Taco' } },
    { id: 'rice', emoji: '🍚', label: { ko: '밥', en: 'Rice' } },
    { id: 'bento', emoji: '🍱', label: { ko: '도시락', en: 'Bento' } },
    { id: 'ramen', emoji: '🍜', label: { ko: '라면', en: 'Ramen' } },
    { id: 'sushi', emoji: '🍣', label: { ko: '초밥', en: 'Sushi' } },
    { id: 'dumpling', emoji: '🥟', label: { ko: '만두', en: 'Dumpling' } },
    { id: 'kbbq', emoji: '🥩', label: { ko: '고기', en: 'Meat' } },
    { id: 'chickenfood', emoji: '🍗', label: { ko: '치킨', en: 'Chicken' } },
    { id: 'egg', emoji: '🍳', label: { ko: '계란', en: 'Egg' } },
    { id: 'salad', emoji: '🥗', label: { ko: '샐러드', en: 'Salad' } },
    { id: 'apple', emoji: '🍎', label: { ko: '사과', en: 'Apple' } },
    { id: 'strawberry', emoji: '🍓', label: { ko: '딸기', en: 'Strawberry' } },
    { id: 'watermelon', emoji: '🍉', label: { ko: '수박', en: 'Melon' } },
    { id: 'grape', emoji: '🍇', label: { ko: '포도', en: 'Grape' } },
    { id: 'peach', emoji: '🍑', label: { ko: '복숭아', en: 'Peach' } },
    { id: 'banana', emoji: '🍌', label: { ko: '바나나', en: 'Banana' } },
    { id: 'music', emoji: '🎵', label: { ko: '음악', en: 'Music' } },
    { id: 'notes', emoji: '🎶', label: { ko: '음표들', en: 'Notes' } },
    { id: 'guitar', emoji: '🎸', label: { ko: '기타', en: 'Guitar' } },
    { id: 'mic', emoji: '🎤', label: { ko: '마이크', en: 'Mic' } },
    { id: 'headphone', emoji: '🎧', label: { ko: '헤드폰', en: 'Headphones' } },
    { id: 'game', emoji: '🎮', label: { ko: '게임', en: 'Game' } },
    { id: 'dice', emoji: '🎲', label: { ko: '주사위', en: 'Dice' } },
    { id: 'soccer', emoji: '⚽', label: { ko: '축구', en: 'Soccer' } },
    { id: 'basketball', emoji: '🏀', label: { ko: '농구', en: 'Basketball' } },
    { id: 'baseball', emoji: '⚾', label: { ko: '야구', en: 'Baseball' } },
    { id: 'tennis', emoji: '🎾', label: { ko: '테니스', en: 'Tennis' } },
    { id: 'run', emoji: '🏃', label: { ko: '달리기', en: 'Run' } },
    { id: 'dance', emoji: '💃', label: { ko: '춤', en: 'Dance' } },
    { id: 'car', emoji: '🚗', label: { ko: '자동차', en: 'Car' } },
    { id: 'taxi', emoji: '🚕', label: { ko: '택시', en: 'Taxi' } },
    { id: 'bus', emoji: '🚌', label: { ko: '버스', en: 'Bus' } },
    { id: 'train', emoji: '🚆', label: { ko: '기차', en: 'Train' } },
    { id: 'plane', emoji: '✈️', label: { ko: '비행기', en: 'Plane' } },
    { id: 'rocket', emoji: '🚀', label: { ko: '로켓', en: 'Rocket' } },
    { id: 'ship', emoji: '🚢', label: { ko: '배', en: 'Ship' } },
    { id: 'bike', emoji: '🚲', label: { ko: '자전거', en: 'Bike' } },
    { id: 'home', emoji: '🏠', label: { ko: '집', en: 'Home' } },
    { id: 'office', emoji: '🏢', label: { ko: '회사', en: 'Office' } },
    { id: 'school', emoji: '🏫', label: { ko: '학교', en: 'School' } },
    { id: 'hospital', emoji: '🏥', label: { ko: '병원', en: 'Hospital' } },
    { id: 'church', emoji: '⛪', label: { ko: '교회', en: 'Church' } },
    { id: 'phone', emoji: '📱', label: { ko: '폰', en: 'Phone' } },
    { id: 'pc', emoji: '💻', label: { ko: '컴퓨터', en: 'PC' } },
    { id: 'keyboard', emoji: '⌨️', label: { ko: '키보드', en: 'Keyboard' } },
    { id: 'tv', emoji: '📺', label: { ko: '티비', en: 'TV' } },
    { id: 'camera', emoji: '📷', label: { ko: '카메라', en: 'Camera' } },
    { id: 'movie', emoji: '🎬', label: { ko: '영화', en: 'Movie' } },
    { id: 'book', emoji: '📚', label: { ko: '책', en: 'Books' } },
    { id: 'mail', emoji: '✉️', label: { ko: '편지', en: 'Mail' } },
    { id: 'link', emoji: '🔗', label: { ko: '링크', en: 'Link' } },
    { id: 'lock', emoji: '🔒', label: { ko: '잠금', en: 'Lock' } },
    { id: 'key', emoji: '🔑', label: { ko: '열쇠', en: 'Key' } },
    { id: 'moneybag', emoji: '💰', label: { ko: '돈주머니', en: 'Money bag' } },
    { id: 'won', emoji: '💵', label: { ko: '현금', en: 'Cash' } },
    { id: 'chartup', emoji: '📈', label: { ko: '상승', en: 'Up chart' } },
    { id: 'chartdown', emoji: '📉', label: { ko: '하락', en: 'Down chart' } },
    { id: 'warning', emoji: '⚠️', label: { ko: '주의', en: 'Warning' } },
    { id: 'stop', emoji: '🛑', label: { ko: '정지', en: 'Stop' } },
    { id: 'recycle', emoji: '♻️', label: { ko: '재활용', en: 'Recycle' } },
    { id: 'kr', emoji: '🇰🇷', label: { ko: '한국', en: 'Korea' } },
    { id: 'clock', emoji: '⏰', label: { ko: '알람', en: 'Alarm' } },
    { id: 'hourglass', emoji: '⏳', label: { ko: '모래시계', en: 'Hourglass' } },
    { id: 'crown', emoji: '👑', label: { ko: '왕관', en: 'Crown' } },
    { id: 'gem', emoji: '💎', label: { ko: '보석', en: 'Gem' } },
    { id: 'ring', emoji: '💍', label: { ko: '반지', en: 'Ring' } },
    { id: 'lipstick', emoji: '💄', label: { ko: '립스틱', en: 'Lipstick' } },
    { id: 'glasses', emoji: '👓', label: { ko: '안경', en: 'Glasses' } },
    { id: 'tshirt', emoji: '👕', label: { ko: '티셔츠', en: 'Shirt' } },
    { id: 'dress', emoji: '👗', label: { ko: '드레스', en: 'Dress' } },
    { id: 'shoes', emoji: '👟', label: { ko: '운동화', en: 'Shoes' } },
    { id: 'bag', emoji: '👜', label: { ko: '가방', en: 'Bag' } },
    { id: 'drop', emoji: '💧', label: { ko: '물방울', en: 'Drop' } },
    { id: 'earth', emoji: '🌍', label: { ko: '지구', en: 'Earth' } },
    { id: 'night', emoji: '🌃', label: { ko: '밤', en: 'Night' } },
    { id: 'sunrise', emoji: '🌅', label: { ko: '일출', en: 'Sunrise' } },
    { id: 'partying', emoji: '🥳', label: { ko: '파티얼굴', en: 'Partying' } },
    { id: 'pleading', emoji: '🥺', label: { ko: '애원', en: 'Pleading' } },
    { id: 'salute', emoji: '🫡', label: { ko: '경례', en: 'Salute' } },
    { id: 'peek', emoji: '🫣', label: { ko: '훔쳐봄', en: 'Peek' } },
    { id: 'melting', emoji: '🫠', label: { ko: '녹음', en: 'Melting' } },
    { id: 'dotted', emoji: '🫥', label: { ko: '점선', en: 'Dotted' } },
];

export function stickerById(id: string): Sticker | undefined {
    return STICKERS.find((item) => item.id === id);
}

export function stickerToken(id: string): string {
    return `[[s:${id}]]`;
}

export function imageToken(id: number): string {
    return `[[i:${id}]]`;
}
