export type Sticker = {
    id: string;
    emoji: string;
    label: { ko: string; en: string };
};

export const STICKERS: Sticker[] = [
    { id: 'love', emoji: '😍', label: { ko: '사랑', en: 'Love' } },
    { id: 'heart', emoji: '❤️', label: { ko: '하트', en: 'Heart' } },
    { id: 'hearts', emoji: '💕', label: { ko: '하트들', en: 'Hearts' } },
    { id: 'kiss', emoji: '😘', label: { ko: '뽀뽀', en: 'Kiss' } },
    { id: 'blush', emoji: '☺️', label: { ko: '수줍', en: 'Blush' } },
    { id: 'like', emoji: '👍', label: { ko: '좋아요', en: 'Like' } },
    { id: 'dislike', emoji: '👎', label: { ko: '싫어요', en: 'Dislike' } },
    { id: 'ok', emoji: '😊', label: { ko: '미소', en: 'Smile' } },
    { id: 'grin', emoji: '😁', label: { ko: '활짝', en: 'Grin' } },
    { id: 'beaming', emoji: '😄', label: { ko: '방긋', en: 'Beaming' } },
    { id: 'lol', emoji: '😂', label: { ko: '웃겨', en: 'LOL' } },
    { id: 'rofl', emoji: '🤣', label: { ko: '폭소', en: 'ROFL' } },
    { id: 'joy', emoji: '😆', label: { ko: '깔깔', en: 'Joy' } },
    { id: 'wink', emoji: '😉', label: { ko: '윙크', en: 'Wink' } },
    { id: 'cool', emoji: '😎', label: { ko: '멋짐', en: 'Cool' } },
    { id: 'nerd', emoji: '🤓', label: { ko: '똑똑', en: 'Nerd' } },
    { id: 'think', emoji: '🤔', label: { ko: '생각', en: 'Think' } },
    { id: 'hmm', emoji: '🧐', label: { ko: '관찰', en: 'Hmm' } },
    { id: 'wow', emoji: '😮', label: { ko: '놀람', en: 'Wow' } },
    { id: 'open', emoji: '😯', label: { ko: '헉', en: 'Gasp' } },
    { id: 'scream', emoji: '😱', label: { ko: '충격', en: 'Shock' } },
    { id: 'fear', emoji: '😨', label: { ko: '무서워', en: 'Fear' } },
    { id: 'sad', emoji: '😢', label: { ko: '슬픔', en: 'Sad' } },
    { id: 'cry', emoji: '😭', label: { ko: '울음', en: 'Cry' } },
    { id: 'sweat', emoji: '😅', label: { ko: '식은땀', en: 'Sweat' } },
    { id: 'tired', emoji: '😫', label: { ko: '지쳐', en: 'Tired' } },
    { id: 'angry', emoji: '😡', label: { ko: '화남', en: 'Angry' } },
    { id: 'mad', emoji: '🤬', label: { ko: '열받음', en: 'Mad' } },
    { id: 'sick', emoji: '🤒', label: { ko: '아픔', en: 'Sick' } },
    { id: 'mask', emoji: '😷', label: { ko: '마스크', en: 'Mask' } },
    { id: 'sleepy', emoji: '😴', label: { ko: '졸림', en: 'Sleepy' } },
    { id: 'yawn', emoji: '🥱', label: { ko: '하품', en: 'Yawn' } },
    { id: 'thanks', emoji: '🙏', label: { ko: '감사', en: 'Thanks' } },
    { id: 'clap', emoji: '👏', label: { ko: '박수', en: 'Clap' } },
    { id: 'wave', emoji: '👋', label: { ko: '안녕', en: 'Hi' } },
    { id: 'flex', emoji: '💪', label: { ko: '힘냄', en: 'Strong' } },
    { id: 'punch', emoji: '👊', label: { ko: '주먹', en: 'Punch' } },
    { id: 'peace', emoji: '✌️', label: { ko: '피스', en: 'Peace' } },
    { id: 'okhand', emoji: '👌', label: { ko: '오케이', en: 'OK' } },
    { id: 'fingers', emoji: '🤞', label: { ko: '행운', en: 'Luck' } },
    { id: 'party', emoji: '🎉', label: { ko: '축하', en: 'Party' } },
    { id: 'tada', emoji: '🎊', label: { ko: '축하해', en: 'Confetti' } },
    { id: 'gift', emoji: '🎁', label: { ko: '선물', en: 'Gift' } },
    { id: 'balloon', emoji: '🎈', label: { ko: '풍선', en: 'Balloon' } },
    { id: 'fire', emoji: '🔥', label: { ko: '대박', en: 'Fire' } },
    { id: 'best', emoji: '🏆', label: { ko: '최고', en: 'Best' } },
    { id: 'medal', emoji: '🥇', label: { ko: '1등', en: 'Gold' } },
    { id: 'star', emoji: '⭐', label: { ko: '별', en: 'Star' } },
    { id: 'glowstar', emoji: '🌟', label: { ko: '반짝별', en: 'Glow' } },
    { id: 'hundred', emoji: '💯', label: { ko: '백점', en: '100' } },
    { id: 'sparkle', emoji: '✨', label: { ko: '반짝', en: 'Sparkle' } },
    { id: 'check', emoji: '✅', label: { ko: '확인', en: 'Check' } },
    { id: 'cross', emoji: '❌', label: { ko: '아니', en: 'No' } },
    { id: 'question', emoji: '❓', label: { ko: '질문', en: 'Question' } },
    { id: 'bang', emoji: '❗', label: { ko: '강조', en: 'Bang' } },
    { id: 'idea', emoji: '💡', label: { ko: '아이디어', en: 'Idea' } },
    { id: 'memo', emoji: '📝', label: { ko: '메모', en: 'Memo' } },
    { id: 'pin', emoji: '📌', label: { ko: '고정', en: 'Pin' } },
    { id: 'bell', emoji: '🔔', label: { ko: '알림', en: 'Bell' } },
    { id: 'eyes', emoji: '👀', label: { ko: '관심', en: 'Eyes' } },
    { id: 'tongue', emoji: '😛', label: { ko: '메롱', en: 'Tongue' } },
    { id: 'silly', emoji: '🤪', label: { ko: '장난', en: 'Silly' } },
    { id: 'angel', emoji: '😇', label: { ko: '천사', en: 'Angel' } },
    { id: 'devil', emoji: '😈', label: { ko: '장난꾸러기', en: 'Devil' } },
    { id: 'poop', emoji: '💩', label: { ko: '똥', en: 'Poop' } },
    { id: 'ghost', emoji: '👻', label: { ko: '유령', en: 'Ghost' } },
    { id: 'robot', emoji: '🤖', label: { ko: '로봇', en: 'Robot' } },
    { id: 'alien', emoji: '👽', label: { ko: '외계인', en: 'Alien' } },
    { id: 'cat', emoji: '🐱', label: { ko: '고양이', en: 'Cat' } },
    { id: 'dog', emoji: '🐶', label: { ko: '강아지', en: 'Dog' } },
    { id: 'bear', emoji: '🐻', label: { ko: '곰', en: 'Bear' } },
    { id: 'panda', emoji: '🐼', label: { ko: '팬더', en: 'Panda' } },
    { id: 'fox', emoji: '🦊', label: { ko: '여우', en: 'Fox' } },
    { id: 'rabbit', emoji: '🐰', label: { ko: '토끼', en: 'Rabbit' } },
    { id: 'unicorn', emoji: '🦄', label: { ko: '유니콘', en: 'Unicorn' } },
    { id: 'sun', emoji: '☀️', label: { ko: '해', en: 'Sun' } },
    { id: 'moon', emoji: '🌙', label: { ko: '달', en: 'Moon' } },
    { id: 'rainbow', emoji: '🌈', label: { ko: '무지개', en: 'Rainbow' } },
    { id: 'cloud', emoji: '☁️', label: { ko: '구름', en: 'Cloud' } },
    { id: 'rain', emoji: '🌧️', label: { ko: '비', en: 'Rain' } },
    { id: 'snow', emoji: '❄️', label: { ko: '눈', en: 'Snow' } },
    { id: 'coffee', emoji: '☕', label: { ko: '커피', en: 'Coffee' } },
    { id: 'tea', emoji: '🍵', label: { ko: '차', en: 'Tea' } },
    { id: 'beer', emoji: '🍺', label: { ko: '맥주', en: 'Beer' } },
    { id: 'cake', emoji: '🎂', label: { ko: '케이크', en: 'Cake' } },
    { id: 'food', emoji: '🍔', label: { ko: '음식', en: 'Food' } },
    { id: 'pizza', emoji: '🍕', label: { ko: '피자', en: 'Pizza' } },
    { id: 'rice', emoji: '🍚', label: { ko: '밥', en: 'Rice' } },
    { id: 'ramen', emoji: '🍜', label: { ko: '라면', en: 'Ramen' } },
    { id: 'music', emoji: '🎵', label: { ko: '음악', en: 'Music' } },
    { id: 'guitar', emoji: '🎸', label: { ko: '기타', en: 'Guitar' } },
    { id: 'game', emoji: '🎮', label: { ko: '게임', en: 'Game' } },
    { id: 'soccer', emoji: '⚽', label: { ko: '축구', en: 'Soccer' } },
    { id: 'car', emoji: '🚗', label: { ko: '자동차', en: 'Car' } },
    { id: 'plane', emoji: '✈️', label: { ko: '비행기', en: 'Plane' } },
    { id: 'home', emoji: '🏠', label: { ko: '집', en: 'Home' } },
    { id: 'phone', emoji: '📱', label: { ko: '폰', en: 'Phone' } },
    { id: 'pc', emoji: '💻', label: { ko: '컴퓨터', en: 'PC' } },
    { id: 'link', emoji: '🔗', label: { ko: '링크', en: 'Link' } },
];

export function stickerById(id: string): Sticker | undefined {
    return STICKERS.find((item) => item.id === id);
}

export function stickerToken(id: string): string {
    return `[[s:${id}]]`;
}

export function imageToken(id: number): string {
    return `[[i:${id}]]`;
}
