export type Sticker = {
    id: string;
    emoji: string;
    label: { ko: string; en: string };
};

export const STICKERS: Sticker[] = [
    { id: 'love', emoji: '😍', label: { ko: '사랑', en: 'Love' } },
    { id: 'heart', emoji: '❤️', label: { ko: '하트', en: 'Heart' } },
    { id: 'hearts', emoji: '💕', label: { ko: '하트들', en: 'Hearts' } },
    { id: 'sparkheart', emoji: '💖', label: { ko: '반짝하트', en: 'Sparkle heart' } },
    { id: 'twohearts', emoji: '💗', label: { ko: '두하트', en: 'Growing heart' } },
    { id: 'revheart', emoji: '💞', label: { ko: '도는하트', en: 'Revolving' } },
    { id: 'beatheart', emoji: '💓', label: { ko: '두근', en: 'Beating' } },
    { id: 'brokenheart', emoji: '💔', label: { ko: '상심', en: 'Broken' } },
    { id: 'blackheart', emoji: '🖤', label: { ko: '검은하트', en: 'Black heart' } },
    { id: 'whiteheart', emoji: '🤍', label: { ko: '흰하트', en: 'White heart' } },
    { id: 'orangeheart', emoji: '🧡', label: { ko: '주황하트', en: 'Orange heart' } },
    { id: 'yellowheart', emoji: '💛', label: { ko: '노란하트', en: 'Yellow heart' } },
    { id: 'greenheart', emoji: '💚', label: { ko: '초록하트', en: 'Green heart' } },
    { id: 'blueheart', emoji: '💙', label: { ko: '파란하트', en: 'Blue heart' } },
    { id: 'purpleheart', emoji: '💜', label: { ko: '보라하트', en: 'Purple heart' } },
    { id: 'brownheart', emoji: '🤎', label: { ko: '갈색하트', en: 'Brown heart' } },
    { id: 'kiss', emoji: '😘', label: { ko: '뽀뽀', en: 'Kiss' } },
    { id: 'kissface', emoji: '😗', label: { ko: '키스', en: 'Kissing' } },
    { id: 'kisswink', emoji: '😙', label: { ko: '윙키스', en: 'Kiss smile' } },
    { id: 'kissclosed', emoji: '😚', label: { ko: '눈감키스', en: 'Kiss closed' } },
    { id: 'blush', emoji: '☺️', label: { ko: '수줍', en: 'Blush' } },
    { id: 'like', emoji: '👍', label: { ko: '좋아요', en: 'Like' } },
    { id: 'dislike', emoji: '👎', label: { ko: '싫어요', en: 'Dislike' } },
    { id: 'ok', emoji: '😊', label: { ko: '미소', en: 'Smile' } },
    { id: 'slight', emoji: '🙂', label: { ko: '살짝', en: 'Slight' } },
    { id: 'upside', emoji: '🙃', label: { ko: '뒤집힌', en: 'Upside down' } },
    { id: 'grin', emoji: '😁', label: { ko: '활짝', en: 'Grin' } },
    { id: 'beaming', emoji: '😄', label: { ko: '방긋', en: 'Beaming' } },
    { id: 'smile', emoji: '😃', label: { ko: '웃음', en: 'Smile' } },
    { id: 'lol', emoji: '😂', label: { ko: '웃겨', en: 'LOL' } },
    { id: 'rofl', emoji: '🤣', label: { ko: '폭소', en: 'ROFL' } },
    { id: 'joy', emoji: '😆', label: { ko: '깔깔', en: 'Joy' } },
    { id: 'wink', emoji: '😉', label: { ko: '윙크', en: 'Wink' } },
    { id: 'cool', emoji: '😎', label: { ko: '멋짐', en: 'Cool' } },
    { id: 'nerd', emoji: '🤓', label: { ko: '똑똑', en: 'Nerd' } },
    { id: 'think', emoji: '🤔', label: { ko: '생각', en: 'Think' } },
    { id: 'hmm', emoji: '🧐', label: { ko: '관찰', en: 'Hmm' } },
    { id: 'wow', emoji: '😮', label: { ko: '놀람', en: 'Wow' } },
    { id: 'open', emoji: '😯', label: { ko: '헉', en: 'Gasp' } },
    { id: 'scream', emoji: '😱', label: { ko: '충격', en: 'Shock' } },
    { id: 'fear', emoji: '😨', label: { ko: '무서워', en: 'Fear' } },
    { id: 'anxious', emoji: '😰', label: { ko: '불안', en: 'Anxious' } },
    { id: 'cold', emoji: '🥶', label: { ko: '추워', en: 'Cold' } },
    { id: 'hot', emoji: '🥵', label: { ko: '더워', en: 'Hot' } },
    { id: 'sad', emoji: '😢', label: { ko: '슬픔', en: 'Sad' } },
    { id: 'cry', emoji: '😭', label: { ko: '울음', en: 'Cry' } },
    { id: 'sweat', emoji: '😅', label: { ko: '식은땀', en: 'Sweat' } },
    { id: 'tired', emoji: '😫', label: { ko: '지쳐', en: 'Tired' } },
    { id: 'weary', emoji: '😩', label: { ko: '힘듦', en: 'Weary' } },
    { id: 'pensive', emoji: '😔', label: { ko: '시무룩', en: 'Pensive' } },
    { id: 'disappointed', emoji: '😞', label: { ko: '실망', en: 'Disappointed' } },
    { id: 'worried', emoji: '😟', label: { ko: '걱정', en: 'Worried' } },
    { id: 'confound', emoji: '😖', label: { ko: '괴로움', en: 'Confounded' } },
    { id: 'persevere', emoji: '😣', label: { ko: '참음', en: 'Persevere' } },
    { id: 'angry', emoji: '😡', label: { ko: '화남', en: 'Angry' } },
    { id: 'mad', emoji: '🤬', label: { ko: '열받음', en: 'Mad' } },
    { id: 'pout', emoji: '😤', label: { ko: '흥', en: 'Humph' } },
    { id: 'sick', emoji: '🤒', label: { ko: '아픔', en: 'Sick' } },
    { id: 'mask', emoji: '😷', label: { ko: '마스크', en: 'Mask' } },
    { id: 'nauseated', emoji: '🤢', label: { ko: '메스꺼움', en: 'Nauseated' } },
    { id: 'vomit', emoji: '🤮', label: { ko: '토함', en: 'Vomit' } },
    { id: 'dizzy', emoji: '😵', label: { ko: '어지러움', en: 'Dizzy' } },
    { id: 'explode', emoji: '🤯', label: { ko: '멘붕', en: 'Mind blown' } },
    { id: 'sleepy', emoji: '😴', label: { ko: '졸림', en: 'Sleepy' } },
    { id: 'yawn', emoji: '🥱', label: { ko: '하품', en: 'Yawn' } },
    { id: 'drool', emoji: '🤤', label: { ko: '침', en: 'Drool' } },
    { id: 'zany', emoji: '😜', label: { ko: '윙메롱', en: 'Zany' } },
    { id: 'money', emoji: '🤑', label: { ko: '돈', en: 'Money' } },
    { id: 'shush', emoji: '🤫', label: { ko: '쉿', en: 'Shush' } },
    { id: 'handmouth', emoji: '🤭', label: { ko: '손으로가림', en: 'Oops' } },
    { id: 'liar', emoji: '🤥', label: { ko: '거짓말', en: 'Lie' } },
    { id: 'neutral', emoji: '😐', label: { ko: '무표정', en: 'Neutral' } },
    { id: 'expressionless', emoji: '😑', label: { ko: '담담', en: 'Blank' } },
    { id: 'unamused', emoji: '😒', label: { ko: '시큰둥', en: 'Unamused' } },
    { id: 'rolling', emoji: '🙄', label: { ko: '눈굴림', en: 'Eye roll' } },
    { id: 'grimace', emoji: '😬', label: { ko: '찌푸림', en: 'Grimace' } },
    { id: 'relieved', emoji: '😌', label: { ko: '안도', en: 'Relieved' } },
    { id: 'smirk', emoji: '😏', label: { ko: '히죽', en: 'Smirk' } },
    { id: 'sleepface', emoji: '😪', label: { ko: '비몽', en: 'Sleepy face' } },
    { id: 'thanks', emoji: '🙏', label: { ko: '감사', en: 'Thanks' } },
    { id: 'clap', emoji: '👏', label: { ko: '박수', en: 'Clap' } },
    { id: 'wave', emoji: '👋', label: { ko: '안녕', en: 'Hi' } },
    { id: 'flex', emoji: '💪', label: { ko: '힘냄', en: 'Strong' } },
    { id: 'punch', emoji: '👊', label: { ko: '주먹', en: 'Punch' } },
    { id: 'fist', emoji: '✊', label: { ko: '주먹쥐기', en: 'Fist' } },
    { id: 'leftfist', emoji: '🤛', label: { ko: '왼주먹', en: 'Left fist' } },
    { id: 'rightfist', emoji: '🤜', label: { ko: '오른주먹', en: 'Right fist' } },
    { id: 'peace', emoji: '✌️', label: { ko: '피스', en: 'Peace' } },
    { id: 'okhand', emoji: '👌', label: { ko: '오케이', en: 'OK' } },
    { id: 'fingers', emoji: '🤞', label: { ko: '행운', en: 'Luck' } },
    { id: 'loveu', emoji: '🤟', label: { ko: '사랑해손', en: 'Love you' } },
    { id: 'horns', emoji: '🤘', label: { ko: '락', en: 'Rock' } },
    { id: 'callme', emoji: '🤙', label: { ko: '전화해', en: 'Call me' } },
    { id: 'pointup', emoji: '☝️', label: { ko: '위', en: 'Up' } },
    { id: 'pointup2', emoji: '👆', label: { ko: '위쪽', en: 'Up 2' } },
    { id: 'pointdown', emoji: '👇', label: { ko: '아래', en: 'Down' } },
    { id: 'pointleft', emoji: '👈', label: { ko: '왼쪽', en: 'Left' } },
    { id: 'pointright', emoji: '👉', label: { ko: '오른쪽', en: 'Right' } },
    { id: 'palm', emoji: '✋', label: { ko: '손바닥', en: 'Palm' } },
    { id: 'raised', emoji: '🤚', label: { ko: '손등', en: 'Raised' } },
    { id: 'splay', emoji: '🖐️', label: { ko: '쫙', en: 'Splayed' } },
    { id: 'vulcan', emoji: '🖖', label: { ko: '벌칸', en: 'Vulcan' } },
    { id: 'selfie', emoji: '🤳', label: { ko: '셀카', en: 'Selfie' } },
    { id: 'nail', emoji: '💅', label: { ko: '네일', en: 'Nails' } },
    { id: 'writehand', emoji: '✍️', label: { ko: '글씨', en: 'Writing' } },
    { id: 'prayfold', emoji: '🤲', label: { ko: '모음', en: 'Palms' } },
    { id: 'handshake', emoji: '🤝', label: { ko: '악수', en: 'Handshake' } },
    { id: 'hug', emoji: '🤗', label: { ko: '포옹', en: 'Hug' } },
    { id: 'party', emoji: '🎉', label: { ko: '축하', en: 'Party' } },
    { id: 'tada', emoji: '🎊', label: { ko: '축하해', en: 'Confetti' } },
    { id: 'gift', emoji: '🎁', label: { ko: '선물', en: 'Gift' } },
    { id: 'balloon', emoji: '🎈', label: { ko: '풍선', en: 'Balloon' } },
    { id: 'ribbon', emoji: '🎀', label: { ko: '리본', en: 'Ribbon' } },
    { id: 'ticket', emoji: '🎫', label: { ko: '티켓', en: 'Ticket' } },
    { id: 'fire', emoji: '🔥', label: { ko: '대박', en: 'Fire' } },
    { id: 'best', emoji: '🏆', label: { ko: '최고', en: 'Best' } },
    { id: 'medal', emoji: '🥇', label: { ko: '1등', en: 'Gold' } },
    { id: 'silver', emoji: '🥈', label: { ko: '2등', en: 'Silver' } },
    { id: 'bronze', emoji: '🥉', label: { ko: '3등', en: 'Bronze' } },
    { id: 'star', emoji: '⭐', label: { ko: '별', en: 'Star' } },
    { id: 'glowstar', emoji: '🌟', label: { ko: '반짝별', en: 'Glow' } },
    { id: 'dizzystar', emoji: '💫', label: { ko: '어지별', en: 'Dizzy star' } },
    { id: 'hundred', emoji: '💯', label: { ko: '백점', en: '100' } },
    { id: 'sparkle', emoji: '✨', label: { ko: '반짝', en: 'Sparkle' } },
    { id: 'boom', emoji: '💥', label: { ko: '펑', en: 'Boom' } },
    { id: 'zzz', emoji: '💤', label: { ko: '쿨쿨', en: 'Zzz' } },
    { id: 'sweatdrop', emoji: '💦', label: { ko: '땀', en: 'Sweat drop' } },
    { id: 'dash', emoji: '💨', label: { ko: '질주', en: 'Dash' } },
    { id: 'check', emoji: '✅', label: { ko: '확인', en: 'Check' } },
    { id: 'cross', emoji: '❌', label: { ko: '아니', en: 'No' } },
    { id: 'question', emoji: '❓', label: { ko: '질문', en: 'Question' } },
    { id: 'bang', emoji: '❗', label: { ko: '강조', en: 'Bang' } },
    { id: 'exclaimq', emoji: '⁉️', label: { ko: '뭐야', en: 'Exclaim q' } },
    { id: 'doublebang', emoji: '‼️', label: { ko: '진짜', en: 'Double bang' } },
    { id: 'idea', emoji: '💡', label: { ko: '아이디어', en: 'Idea' } },
    { id: 'memo', emoji: '📝', label: { ko: '메모', en: 'Memo' } },
    { id: 'pin', emoji: '📌', label: { ko: '고정', en: 'Pin' } },
    { id: 'bell', emoji: '🔔', label: { ko: '알림', en: 'Bell' } },
    { id: 'megaphone', emoji: '📢', label: { ko: '확성기', en: 'Mega' } },
    { id: 'eyes', emoji: '👀', label: { ko: '관심', en: 'Eyes' } },
    { id: 'tongue', emoji: '😛', label: { ko: '메롱', en: 'Tongue' } },
    { id: 'silly', emoji: '🤪', label: { ko: '장난', en: 'Silly' } },
    { id: 'angel', emoji: '😇', label: { ko: '천사', en: 'Angel' } },
    { id: 'devil', emoji: '😈', label: { ko: '장난꾸러기', en: 'Devil' } },
    { id: 'imp', emoji: '👿', label: { ko: '삐짐', en: 'Imp' } },
    { id: 'skull', emoji: '💀', label: { ko: '해골', en: 'Skull' } },
    { id: 'poop', emoji: '💩', label: { ko: '똥', en: 'Poop' } },
    { id: 'ghost', emoji: '👻', label: { ko: '유령', en: 'Ghost' } },
    { id: 'robot', emoji: '🤖', label: { ko: '로봇', en: 'Robot' } },
    { id: 'alien', emoji: '👽', label: { ko: '외계인', en: 'Alien' } },
    { id: 'clown', emoji: '🤡', label: { ko: '광대', en: 'Clown' } },
    { id: 'ogre', emoji: '👹', label: { ko: '도깨비', en: 'Ogre' } },
    { id: 'goblin', emoji: '👺', label: { ko: '천구', en: 'Goblin' } },
    { id: 'jack', emoji: '🎃', label: { ko: '호박', en: 'Pumpkin' } },
    { id: 'cat', emoji: '🐱', label: { ko: '고양이', en: 'Cat' } },
    { id: 'catgrin', emoji: '😺', label: { ko: '고양미소', en: 'Cat grin' } },
    { id: 'catjoy', emoji: '😹', label: { ko: '고양웃음', en: 'Cat joy' } },
    { id: 'catheart', emoji: '😻', label: { ko: '고양사랑', en: 'Cat love' } },
    { id: 'catsmirk', emoji: '😼', label: { ko: '고양히죽', en: 'Cat smirk' } },
    { id: 'catkiss', emoji: '😽', label: { ko: '고양뽀뽀', en: 'Cat kiss' } },
    { id: 'catscream', emoji: '🙀', label: { ko: '고양헉', en: 'Cat scream' } },
    { id: 'catcry', emoji: '😿', label: { ko: '고양울음', en: 'Cat cry' } },
    { id: 'catpout', emoji: '😾', label: { ko: '고양삐짐', en: 'Cat pout' } },
    { id: 'dog', emoji: '🐶', label: { ko: '강아지', en: 'Dog' } },
    { id: 'bear', emoji: '🐻', label: { ko: '곰', en: 'Bear' } },
    { id: 'panda', emoji: '🐼', label: { ko: '팬더', en: 'Panda' } },
    { id: 'fox', emoji: '🦊', label: { ko: '여우', en: 'Fox' } },
    { id: 'rabbit', emoji: '🐰', label: { ko: '토끼', en: 'Rabbit' } },
    { id: 'tiger', emoji: '🐯', label: { ko: '호랑이', en: 'Tiger' } },
    { id: 'lion', emoji: '🦁', label: { ko: '사자', en: 'Lion' } },
    { id: 'cow', emoji: '🐮', label: { ko: '소', en: 'Cow' } },
    { id: 'pig', emoji: '🐷', label: { ko: '돼지', en: 'Pig' } },
    { id: 'frog', emoji: '🐸', label: { ko: '개구리', en: 'Frog' } },
    { id: 'monkey', emoji: '🐵', label: { ko: '원숭이', en: 'Monkey' } },
    { id: 'see', emoji: '🙈', label: { ko: '안보임', en: 'See no' } },
    { id: 'hear', emoji: '🙉', label: { ko: '안들림', en: 'Hear no' } },
    { id: 'speak', emoji: '🙊', label: { ko: '안말함', en: 'Speak no' } },
    { id: 'chicken', emoji: '🐔', label: { ko: '닭', en: 'Chicken' } },
    { id: 'penguin', emoji: '🐧', label: { ko: '펭귄', en: 'Penguin' } },
    { id: 'bird', emoji: '🐦', label: { ko: '새', en: 'Bird' } },
    { id: 'chick', emoji: '🐥', label: { ko: '병아리', en: 'Chick' } },
    { id: 'owl', emoji: '🦉', label: { ko: '올빼미', en: 'Owl' } },
    { id: 'unicorn', emoji: '🦄', label: { ko: '유니콘', en: 'Unicorn' } },
    { id: 'horse', emoji: '🐴', label: { ko: '말', en: 'Horse' } },
    { id: 'bee', emoji: '🐝', label: { ko: '벌', en: 'Bee' } },
    { id: 'bug', emoji: '🐛', label: { ko: '벌레', en: 'Bug' } },
    { id: 'butterfly', emoji: '🦋', label: { ko: '나비', en: 'Butterfly' } },
    { id: 'turtle', emoji: '🐢', label: { ko: '거북', en: 'Turtle' } },
    { id: 'octopus', emoji: '🐙', label: { ko: '문어', en: 'Octopus' } },
    { id: 'whale', emoji: '🐳', label: { ko: '고래', en: 'Whale' } },
    { id: 'dolphin', emoji: '🐬', label: { ko: '돌고래', en: 'Dolphin' } },
    { id: 'fish', emoji: '🐟', label: { ko: '물고기', en: 'Fish' } },
    { id: 'sun', emoji: '☀️', label: { ko: '해', en: 'Sun' } },
    { id: 'moon', emoji: '🌙', label: { ko: '달', en: 'Moon' } },
    { id: 'fullmoon', emoji: '🌕', label: { ko: '보름달', en: 'Full moon' } },
    { id: 'starstruck', emoji: '🤩', label: { ko: '반함', en: 'Starstruck' } },
    { id: 'rainbow', emoji: '🌈', label: { ko: '무지개', en: 'Rainbow' } },
    { id: 'cloud', emoji: '☁️', label: { ko: '구름', en: 'Cloud' } },
    { id: 'rain', emoji: '🌧️', label: { ko: '비', en: 'Rain' } },
    { id: 'thunder', emoji: '⛈️', label: { ko: '천둥', en: 'Storm' } },
    { id: 'lightning', emoji: '⚡', label: { ko: '번개', en: 'Zap' } },
    { id: 'snow', emoji: '❄️', label: { ko: '눈', en: 'Snow' } },
    { id: 'snowman', emoji: '⛄', label: { ko: '눈사람', en: 'Snowman' } },
    { id: 'umbrella', emoji: '☔', label: { ko: '우산', en: 'Umbrella' } },
    { id: 'flower', emoji: '🌸', label: { ko: '벚꽃', en: 'Cherry' } },
    { id: 'rose', emoji: '🌹', label: { ko: '장미', en: 'Rose' } },
    { id: 'tulip', emoji: '🌷', label: { ko: '튤립', en: 'Tulip' } },
    { id: 'sunflower', emoji: '🌻', label: { ko: '해바라기', en: 'Sunflower' } },
    { id: 'bouquet', emoji: '💐', label: { ko: '꽃다발', en: 'Bouquet' } },
    { id: 'leaf', emoji: '🍀', label: { ko: '네잎', en: 'Clover' } },
    { id: 'tree', emoji: '🌳', label: { ko: '나무', en: 'Tree' } },
    { id: 'coffee', emoji: '☕', label: { ko: '커피', en: 'Coffee' } },
    { id: 'tea', emoji: '🍵', label: { ko: '차', en: 'Tea' } },
    { id: 'bubbletea', emoji: '🧋', label: { ko: '버블티', en: 'Boba' } },
    { id: 'beer', emoji: '🍺', label: { ko: '맥주', en: 'Beer' } },
    { id: 'beers', emoji: '🍻', label: { ko: '건배', en: 'Cheers' } },
    { id: 'wine', emoji: '🍷', label: { ko: '와인', en: 'Wine' } },
    { id: 'sake', emoji: '🍶', label: { ko: '사케', en: 'Sake' } },
    { id: 'soju', emoji: '🥃', label: { ko: '소주', en: 'Soju' } },
    { id: 'cake', emoji: '🎂', label: { ko: '케이크', en: 'Cake' } },
    { id: 'shortcake', emoji: '🍰', label: { ko: '조각케익', en: 'Slice' } },
    { id: 'donut', emoji: '🍩', label: { ko: '도넛', en: 'Donut' } },
    { id: 'cookie', emoji: '🍪', label: { ko: '쿠키', en: 'Cookie' } },
    { id: 'icecream', emoji: '🍦', label: { ko: '아이스크림', en: 'Ice cream' } },
    { id: 'chocolate', emoji: '🍫', label: { ko: '초콜릿', en: 'Chocolate' } },
    { id: 'candy', emoji: '🍬', label: { ko: '사탕', en: 'Candy' } },
    { id: 'lollipop', emoji: '🍭', label: { ko: '막대사탕', en: 'Lollipop' } },
    { id: 'food', emoji: '🍔', label: { ko: '음식', en: 'Food' } },
    { id: 'pizza', emoji: '🍕', label: { ko: '피자', en: 'Pizza' } },
    { id: 'fries', emoji: '🍟', label: { ko: '감자튀김', en: 'Fries' } },
    { id: 'hotdog', emoji: '🌭', label: { ko: '핫도그', en: 'Hotdog' } },
    { id: 'taco', emoji: '🌮', label: { ko: '타코', en: 'Taco' } },
    { id: 'rice', emoji: '🍚', label: { ko: '밥', en: 'Rice' } },
    { id: 'bento', emoji: '🍱', label: { ko: '도시락', en: 'Bento' } },
    { id: 'ramen', emoji: '🍜', label: { ko: '라면', en: 'Ramen' } },
    { id: 'sushi', emoji: '🍣', label: { ko: '초밥', en: 'Sushi' } },
    { id: 'dumpling', emoji: '🥟', label: { ko: '만두', en: 'Dumpling' } },
    { id: 'kbbq', emoji: '🥩', label: { ko: '고기', en: 'Meat' } },
    { id: 'chickenfood', emoji: '🍗', label: { ko: '치킨', en: 'Chicken' } },
    { id: 'egg', emoji: '🍳', label: { ko: '계란', en: 'Egg' } },
    { id: 'salad', emoji: '🥗', label: { ko: '샐러드', en: 'Salad' } },
    { id: 'apple', emoji: '🍎', label: { ko: '사과', en: 'Apple' } },
    { id: 'strawberry', emoji: '🍓', label: { ko: '딸기', en: 'Strawberry' } },
    { id: 'watermelon', emoji: '🍉', label: { ko: '수박', en: 'Melon' } },
    { id: 'grape', emoji: '🍇', label: { ko: '포도', en: 'Grape' } },
    { id: 'peach', emoji: '🍑', label: { ko: '복숭아', en: 'Peach' } },
    { id: 'banana', emoji: '🍌', label: { ko: '바나나', en: 'Banana' } },
    { id: 'music', emoji: '🎵', label: { ko: '음악', en: 'Music' } },
    { id: 'notes', emoji: '🎶', label: { ko: '음표들', en: 'Notes' } },
    { id: 'guitar', emoji: '🎸', label: { ko: '기타', en: 'Guitar' } },
    { id: 'mic', emoji: '🎤', label: { ko: '마이크', en: 'Mic' } },
    { id: 'headphone', emoji: '🎧', label: { ko: '헤드폰', en: 'Headphones' } },
    { id: 'game', emoji: '🎮', label: { ko: '게임', en: 'Game' } },
    { id: 'dice', emoji: '🎲', label: { ko: '주사위', en: 'Dice' } },
    { id: 'soccer', emoji: '⚽', label: { ko: '축구', en: 'Soccer' } },
    { id: 'basketball', emoji: '🏀', label: { ko: '농구', en: 'Basketball' } },
    { id: 'baseball', emoji: '⚾', label: { ko: '야구', en: 'Baseball' } },
    { id: 'tennis', emoji: '🎾', label: { ko: '테니스', en: 'Tennis' } },
    { id: 'run', emoji: '🏃', label: { ko: '달리기', en: 'Run' } },
    { id: 'dance', emoji: '💃', label: { ko: '춤', en: 'Dance' } },
    { id: 'car', emoji: '🚗', label: { ko: '자동차', en: 'Car' } },
    { id: 'taxi', emoji: '🚕', label: { ko: '택시', en: 'Taxi' } },
    { id: 'bus', emoji: '🚌', label: { ko: '버스', en: 'Bus' } },
    { id: 'train', emoji: '🚆', label: { ko: '기차', en: 'Train' } },
    { id: 'plane', emoji: '✈️', label: { ko: '비행기', en: 'Plane' } },
    { id: 'rocket', emoji: '🚀', label: { ko: '로켓', en: 'Rocket' } },
    { id: 'ship', emoji: '🚢', label: { ko: '배', en: 'Ship' } },
    { id: 'bike', emoji: '🚲', label: { ko: '자전거', en: 'Bike' } },
    { id: 'home', emoji: '🏠', label: { ko: '집', en: 'Home' } },
    { id: 'office', emoji: '🏢', label: { ko: '회사', en: 'Office' } },
    { id: 'school', emoji: '🏫', label: { ko: '학교', en: 'School' } },
    { id: 'hospital', emoji: '🏥', label: { ko: '병원', en: 'Hospital' } },
    { id: 'church', emoji: '⛪', label: { ko: '교회', en: 'Church' } },
    { id: 'phone', emoji: '📱', label: { ko: '폰', en: 'Phone' } },
    { id: 'pc', emoji: '💻', label: { ko: '컴퓨터', en: 'PC' } },
    { id: 'keyboard', emoji: '⌨️', label: { ko: '키보드', en: 'Keyboard' } },
    { id: 'tv', emoji: '📺', label: { ko: '티비', en: 'TV' } },
    { id: 'camera', emoji: '📷', label: { ko: '카메라', en: 'Camera' } },
    { id: 'movie', emoji: '🎬', label: { ko: '영화', en: 'Movie' } },
    { id: 'book', emoji: '📚', label: { ko: '책', en: 'Books' } },
    { id: 'mail', emoji: '✉️', label: { ko: '편지', en: 'Mail' } },
    { id: 'link', emoji: '🔗', label: { ko: '링크', en: 'Link' } },
    { id: 'lock', emoji: '🔒', label: { ko: '잠금', en: 'Lock' } },
    { id: 'key', emoji: '🔑', label: { ko: '열쇠', en: 'Key' } },
    { id: 'moneybag', emoji: '💰', label: { ko: '돈주머니', en: 'Money bag' } },
    { id: 'won', emoji: '💵', label: { ko: '현금', en: 'Cash' } },
    { id: 'chartup', emoji: '📈', label: { ko: '상승', en: 'Up chart' } },
    { id: 'chartdown', emoji: '📉', label: { ko: '하락', en: 'Down chart' } },
    { id: 'warning', emoji: '⚠️', label: { ko: '주의', en: 'Warning' } },
    { id: 'stop', emoji: '🛑', label: { ko: '정지', en: 'Stop' } },
    { id: 'recycle', emoji: '♻️', label: { ko: '재활용', en: 'Recycle' } },
    { id: 'kr', emoji: '🇰🇷', label: { ko: '한국', en: 'Korea' } },
    { id: 'clock', emoji: '⏰', label: { ko: '알람', en: 'Alarm' } },
    { id: 'hourglass', emoji: '⏳', label: { ko: '모래시계', en: 'Hourglass' } },
    { id: 'crown', emoji: '👑', label: { ko: '왕관', en: 'Crown' } },
    { id: 'gem', emoji: '💎', label: { ko: '보석', en: 'Gem' } },
    { id: 'ring', emoji: '💍', label: { ko: '반지', en: 'Ring' } },
    { id: 'lipstick', emoji: '💄', label: { ko: '립스틱', en: 'Lipstick' } },
    { id: 'glasses', emoji: '👓', label: { ko: '안경', en: 'Glasses' } },
    { id: 'tshirt', emoji: '👕', label: { ko: '티셔츠', en: 'Shirt' } },
    { id: 'dress', emoji: '👗', label: { ko: '드레스', en: 'Dress' } },
    { id: 'shoes', emoji: '👟', label: { ko: '운동화', en: 'Shoes' } },
    { id: 'bag', emoji: '👜', label: { ko: '가방', en: 'Bag' } },
    { id: 'drop', emoji: '💧', label: { ko: '물방울', en: 'Drop' } },
    { id: 'earth', emoji: '🌍', label: { ko: '지구', en: 'Earth' } },
    { id: 'night', emoji: '🌃', label: { ko: '밤', en: 'Night' } },
    { id: 'sunrise', emoji: '🌅', label: { ko: '일출', en: 'Sunrise' } },
    { id: 'partying', emoji: '🥳', label: { ko: '파티얼굴', en: 'Partying' } },
    { id: 'pleading', emoji: '🥺', label: { ko: '애원', en: 'Pleading' } },
    { id: 'salute', emoji: '🫡', label: { ko: '경례', en: 'Salute' } },
    { id: 'peek', emoji: '🫣', label: { ko: '훔쳐봄', en: 'Peek' } },
    { id: 'melting', emoji: '🫠', label: { ko: '녹음', en: 'Melting' } },
    { id: 'dotted', emoji: '🫥', label: { ko: '점선', en: 'Dotted' } },
    { id: 'zipper', emoji: '🤐', label: { ko: '지퍼입', en: 'Zipper' } },
    { id: 'disguise', emoji: '🥸', label: { ko: '변장', en: 'Disguise' } },
    { id: 'tearsheld', emoji: '🥹', label: { ko: '감동', en: 'Holding tears' } },
    { id: 'exhale', emoji: '😮‍💨', label: { ko: '한숨', en: 'Exhale' } },
    { id: 'inclouds', emoji: '😶‍🌫️', label: { ko: '안개속', en: 'In clouds' } },
    { id: 'spiraleyes', emoji: '😵‍💫', label: { ko: '현기증', en: 'Spiral' } },
    { id: 'hearthands', emoji: '🫶', label: { ko: '하트손', en: 'Heart hands' } },
    { id: 'palmup', emoji: '🫴', label: { ko: '손바닥위', en: 'Palm up' } },
    { id: 'palmdown', emoji: '🫳', label: { ko: '손바닥아래', en: 'Palm down' } },
    { id: 'pushright', emoji: '🫸', label: { ko: '밀기', en: 'Push' } },
    { id: 'pullleft', emoji: '🫷', label: { ko: '당기기', en: 'Pull' } },
    { id: 'righthand', emoji: '🫱', label: { ko: '오른손', en: 'Right hand' } },
    { id: 'lefthand', emoji: '🫲', label: { ko: '왼손', en: 'Left hand' } },
    { id: 'pointyou', emoji: '🫵', label: { ko: '너', en: 'You' } },
    { id: 'heartexclaim', emoji: '❣️', label: { ko: '하트느낌', en: 'Heart bang' } },
    { id: 'heartdeco', emoji: '💟', label: { ko: '하트장식', en: 'Heart deco' } },
    { id: 'cupid', emoji: '💘', label: { ko: '큐피드', en: 'Cupid' } },
    { id: 'giftheart', emoji: '💝', label: { ko: '선물하트', en: 'Gift heart' } },
    { id: 'heartfire', emoji: '❤️‍🔥', label: { ko: '불하트', en: 'Heart fire' } },
    { id: 'pinkheart', emoji: '🩷', label: { ko: '핑크하트', en: 'Pink heart' } },
    { id: 'lightblueheart', emoji: '🩵', label: { ko: '하늘하트', en: 'Light blue' } },
    { id: 'greyheart', emoji: '🩶', label: { ko: '회색하트', en: 'Grey heart' } },
    { id: 'anatomical', emoji: '🫀', label: { ko: '심장', en: 'Anatomical' } },
    { id: 'lungs', emoji: '🫁', label: { ko: '폐', en: 'Lungs' } },
    { id: 'brain', emoji: '🧠', label: { ko: '뇌', en: 'Brain' } },
    { id: 'tooth', emoji: '🦷', label: { ko: '이빨', en: 'Tooth' } },
    { id: 'bone', emoji: '🦴', label: { ko: '뼈', en: 'Bone' } },
    { id: 'eye', emoji: '👁️', label: { ko: '눈', en: 'Eye' } },
    { id: 'bitelip', emoji: '🫦', label: { ko: '입술깨물', en: 'Bite lip' } },
    { id: 'mouth', emoji: '👄', label: { ko: '입술', en: 'Mouth' } },
    { id: 'baby', emoji: '👶', label: { ko: '아기', en: 'Baby' } },
    { id: 'child', emoji: '🧒', label: { ko: '아이', en: 'Child' } },
    { id: 'boy', emoji: '👦', label: { ko: '소년', en: 'Boy' } },
    { id: 'girl', emoji: '👧', label: { ko: '소녀', en: 'Girl' } },
    { id: 'person', emoji: '🧑', label: { ko: '사람', en: 'Person' } },
    { id: 'man', emoji: '👨', label: { ko: '남자', en: 'Man' } },
    { id: 'woman', emoji: '👩', label: { ko: '여자', en: 'Woman' } },
    { id: 'oldman', emoji: '👴', label: { ko: '할아버지', en: 'Old man' } },
    { id: 'oldwoman', emoji: '👵', label: { ko: '할머니', en: 'Old woman' } },
    { id: 'princess', emoji: '👸', label: { ko: '공주', en: 'Princess' } },
    { id: 'prince', emoji: '🤴', label: { ko: '왕자', en: 'Prince' } },
    { id: 'hero', emoji: '🦸', label: { ko: '히어로', en: 'Hero' } },
    { id: 'villain', emoji: '🦹', label: { ko: '빌런', en: 'Villain' } },
    { id: 'mage', emoji: '🧙', label: { ko: '마법사', en: 'Mage' } },
    { id: 'fairy', emoji: '🧚', label: { ko: '요정', en: 'Fairy' } },
    { id: 'vampire', emoji: '🧛', label: { ko: '뱀파이어', en: 'Vampire' } },
    { id: 'mermaid', emoji: '🧜', label: { ko: '인어', en: 'Mermaid' } },
    { id: 'elf', emoji: '🧝', label: { ko: '엘프', en: 'Elf' } },
    { id: 'genie', emoji: '🧞', label: { ko: '지니', en: 'Genie' } },
    { id: 'zombie', emoji: '🧟', label: { ko: '좀비', en: 'Zombie' } },
    { id: 'ninja', emoji: '🥷', label: { ko: '닌자', en: 'Ninja' } },
    { id: 'worker', emoji: '👷', label: { ko: '공사', en: 'Worker' } },
    { id: 'police', emoji: '👮', label: { ko: '경찰', en: 'Police' } },
    { id: 'detective', emoji: '🕵️', label: { ko: '탐정', en: 'Detective' } },
    { id: 'guard', emoji: '💂', label: { ko: '근위병', en: 'Guard' } },
    { id: 'cook', emoji: '🧑‍🍳', label: { ko: '요리사', en: 'Cook' } },
    { id: 'student', emoji: '🧑‍🎓', label: { ko: '학생', en: 'Student' } },
    { id: 'teacher', emoji: '🧑‍🏫', label: { ko: '선생님', en: 'Teacher' } },
    { id: 'farmer', emoji: '🧑‍🌾', label: { ko: '농부', en: 'Farmer' } },
    { id: 'scientist', emoji: '🧑‍🔬', label: { ko: '과학자', en: 'Scientist' } },
    { id: 'artist', emoji: '🧑‍🎨', label: { ko: '화가', en: 'Artist' } },
    { id: 'pilot', emoji: '🧑‍✈️', label: { ko: '조종사', en: 'Pilot' } },
    { id: 'astronaut', emoji: '🧑‍🚀', label: { ko: '우주인', en: 'Astronaut' } },
    { id: 'judge', emoji: '🧑‍⚖️', label: { ko: '판사', en: 'Judge' } },
    { id: 'bride', emoji: '👰', label: { ko: '신부', en: 'Bride' } },
    { id: 'groom', emoji: '🤵', label: { ko: '신랑', en: 'Groom' } },
    { id: 'santa', emoji: '🎅', label: { ko: '산타', en: 'Santa' } },
    { id: 'mrsclaus', emoji: '🤶', label: { ko: '산타할머니', en: 'Mrs Claus' } },
    { id: 'pregnant', emoji: '🤰', label: { ko: '임신', en: 'Pregnant' } },
    { id: 'hamster', emoji: '🐹', label: { ko: '햄스터', en: 'Hamster' } },
    { id: 'mouse', emoji: '🐭', label: { ko: '쥐', en: 'Mouse' } },
    { id: 'koala', emoji: '🐨', label: { ko: '코알라', en: 'Koala' } },
    { id: 'hatch', emoji: '🐣', label: { ko: '알깨기', en: 'Hatch' } },
    { id: 'duck', emoji: '🦆', label: { ko: '오리', en: 'Duck' } },
    { id: 'eagle', emoji: '🦅', label: { ko: '독수리', en: 'Eagle' } },
    { id: 'bat', emoji: '🦇', label: { ko: '박쥐', en: 'Bat' } },
    { id: 'wolf', emoji: '🐺', label: { ko: '늑대', en: 'Wolf' } },
    { id: 'boar', emoji: '🐗', label: { ko: '멧돼지', en: 'Boar' } },
    { id: 'deer', emoji: '🦌', label: { ko: '사슴', en: 'Deer' } },
    { id: 'paw', emoji: '🐾', label: { ko: '발바닥', en: 'Paw' } },
    { id: 'dragon', emoji: '🐉', label: { ko: '용', en: 'Dragon' } },
    { id: 'dragonface', emoji: '🐲', label: { ko: '용얼굴', en: 'Dragon face' } },
    { id: 'dino', emoji: '🦕', label: { ko: '공룡', en: 'Dino' } },
    { id: 'trex', emoji: '🦖', label: { ko: '티렉스', en: 'T-rex' } },
    { id: 'shark', emoji: '🦈', label: { ko: '상어', en: 'Shark' } },
    { id: 'croc', emoji: '🐊', label: { ko: '악어', en: 'Croc' } },
    { id: 'lizard', emoji: '🦎', label: { ko: '도마뱀', en: 'Lizard' } },
    { id: 'snake', emoji: '🐍', label: { ko: '뱀', en: 'Snake' } },
    { id: 'shrimp', emoji: '🦐', label: { ko: '새우', en: 'Shrimp' } },
    { id: 'lobster', emoji: '🦞', label: { ko: '랍스터', en: 'Lobster' } },
    { id: 'crab', emoji: '🦀', label: { ko: '게', en: 'Crab' } },
    { id: 'squid', emoji: '🦑', label: { ko: '오징어', en: 'Squid' } },
    { id: 'oyster', emoji: '🦪', label: { ko: '굴', en: 'Oyster' } },
    { id: 'snail', emoji: '🐌', label: { ko: '달팽이', en: 'Snail' } },
    { id: 'ant', emoji: '🐜', label: { ko: '개미', en: 'Ant' } },
    { id: 'cricket', emoji: '🦗', label: { ko: '귀뚜라미', en: 'Cricket' } },
    { id: 'mosquito', emoji: '🦟', label: { ko: '모기', en: 'Mosquito' } },
    { id: 'worm', emoji: '🪱', label: { ko: '지렁이', en: 'Worm' } },
    { id: 'microbe', emoji: '🦠', label: { ko: '세균', en: 'Microbe' } },
    { id: 'sloth', emoji: '🦥', label: { ko: '나무늘보', en: 'Sloth' } },
    { id: 'otter', emoji: '🦦', label: { ko: '수달', en: 'Otter' } },
    { id: 'skunk', emoji: '🦨', label: { ko: '스컹크', en: 'Skunk' } },
    { id: 'kangaroo', emoji: '🦘', label: { ko: '캥거루', en: 'Kangaroo' } },
    { id: 'hedgehog', emoji: '🦔', label: { ko: '고슴도치', en: 'Hedgehog' } },
    { id: 'chipmunk', emoji: '🐿️', label: { ko: '다람쥐', en: 'Chipmunk' } },
    { id: 'swan', emoji: '🦢', label: { ko: '백조', en: 'Swan' } },
    { id: 'flamingo', emoji: '🦩', label: { ko: '홍학', en: 'Flamingo' } },
    { id: 'peacock', emoji: '🦚', label: { ko: '공작', en: 'Peacock' } },
    { id: 'parrot', emoji: '🦜', label: { ko: '앵무', en: 'Parrot' } },
    { id: 'dodo', emoji: '🦤', label: { ko: '도도', en: 'Dodo' } },
    { id: 'seal', emoji: '🦭', label: { ko: '물개', en: 'Seal' } },
    { id: 'mammoth', emoji: '🦣', label: { ko: '매머드', en: 'Mammoth' } },
    { id: 'bison', emoji: '🦬', label: { ko: '들소', en: 'Bison' } },
    { id: 'beaver', emoji: '🦫', label: { ko: '비버', en: 'Beaver' } },
    { id: 'goat', emoji: '🐐', label: { ko: '염소', en: 'Goat' } },
    { id: 'sheep', emoji: '🐑', label: { ko: '양', en: 'Sheep' } },
    { id: 'ram', emoji: '🐏', label: { ko: '숫양', en: 'Ram' } },
    { id: 'llama', emoji: '🦙', label: { ko: '라마', en: 'Llama' } },
    { id: 'camel', emoji: '🐫', label: { ko: '낙타', en: 'Camel' } },
    { id: 'elephant', emoji: '🐘', label: { ko: '코끼리', en: 'Elephant' } },
    { id: 'rhino', emoji: '🦏', label: { ko: '코뿔소', en: 'Rhino' } },
    { id: 'hippo', emoji: '🦛', label: { ko: '하마', en: 'Hippo' } },
    { id: 'giraffe', emoji: '🦒', label: { ko: '기린', en: 'Giraffe' } },
    { id: 'zebra', emoji: '🦓', label: { ko: '얼룩말', en: 'Zebra' } },
    { id: 'gorilla', emoji: '🦍', label: { ko: '고릴라', en: 'Gorilla' } },
    { id: 'orangutan', emoji: '🦧', label: { ko: '오랑우탄', en: 'Orangutan' } },
    { id: 'leopard', emoji: '🐆', label: { ko: '표범', en: 'Leopard' } },
    { id: 'croissant', emoji: '🥐', label: { ko: '크루아상', en: 'Croissant' } },
    { id: 'baguette', emoji: '🥖', label: { ko: '바게트', en: 'Baguette' } },
    { id: 'pretzel', emoji: '🥨', label: { ko: '프레첼', en: 'Pretzel' } },
    { id: 'bagel', emoji: '🥯', label: { ko: '베이글', en: 'Bagel' } },
    { id: 'pancakes', emoji: '🥞', label: { ko: '팬케이크', en: 'Pancakes' } },
    { id: 'waffle', emoji: '🧇', label: { ko: '와플', en: 'Waffle' } },
    { id: 'cheese', emoji: '🧀', label: { ko: '치즈', en: 'Cheese' } },
    { id: 'bacon', emoji: '🥓', label: { ko: '베이컨', en: 'Bacon' } },
    { id: 'sandwich', emoji: '🥪', label: { ko: '샌드위치', en: 'Sandwich' } },
    { id: 'burrito', emoji: '🌯', label: { ko: '부리또', en: 'Burrito' } },
    { id: 'falafel', emoji: '🧆', label: { ko: '팔라펠', en: 'Falafel' } },
    { id: 'popcorn', emoji: '🍿', label: { ko: '팝콘', en: 'Popcorn' } },
    { id: 'butter', emoji: '🧈', label: { ko: '버터', en: 'Butter' } },
    { id: 'salt', emoji: '🧂', label: { ko: '소금', en: 'Salt' } },
    { id: 'spaghetti', emoji: '🍝', label: { ko: '스파게티', en: 'Spaghetti' } },
    { id: 'curry', emoji: '🍛', label: { ko: '카레', en: 'Curry' } },
    { id: 'onigiri', emoji: '🍙', label: { ko: '주먹밥', en: 'Onigiri' } },
    { id: 'oden', emoji: '🍢', label: { ko: '오뎅', en: 'Oden' } },
    { id: 'dango', emoji: '🍡', label: { ko: '당고', en: 'Dango' } },
    { id: 'shavedice', emoji: '🍧', label: { ko: '빙수', en: 'Shaved ice' } },
    { id: 'pie', emoji: '🥧', label: { ko: '파이', en: 'Pie' } },
    { id: 'custard', emoji: '🍮', label: { ko: '푸딩', en: 'Pudding' } },
    { id: 'honey', emoji: '🍯', label: { ko: '꿀', en: 'Honey' } },
    { id: 'milk', emoji: '🥛', label: { ko: '우유', en: 'Milk' } },
    { id: 'bottle', emoji: '🍾', label: { ko: '샴페인', en: 'Champagne' } },
    { id: 'tropical', emoji: '🍹', label: { ko: '트로피컬', en: 'Tropical' } },
    { id: 'cocktail', emoji: '🍸', label: { ko: '칵테일', en: 'Cocktail' } },
    { id: 'soda', emoji: '🥤', label: { ko: '음료', en: 'Soda' } },
    { id: 'juice', emoji: '🧃', label: { ko: '주스', en: 'Juice' } },
    { id: 'icecube', emoji: '🧊', label: { ko: '얼음', en: 'Ice' } },
    { id: 'chopsticks', emoji: '🥢', label: { ko: '젓가락', en: 'Chopsticks' } },
    { id: 'fork', emoji: '🍴', label: { ko: '포크', en: 'Fork' } },
    { id: 'spoon', emoji: '🥄', label: { ko: '숟가락', en: 'Spoon' } },
    { id: 'greenapple', emoji: '🍏', label: { ko: '초록사과', en: 'Green apple' } },
    { id: 'pear', emoji: '🍐', label: { ko: '배', en: 'Pear' } },
    { id: 'orange', emoji: '🍊', label: { ko: '귤', en: 'Orange' } },
    { id: 'lemon', emoji: '🍋', label: { ko: '레몬', en: 'Lemon' } },
    { id: 'cherries', emoji: '🍒', label: { ko: '체리', en: 'Cherries' } },
    { id: 'pineapple', emoji: '🍍', label: { ko: '파인애플', en: 'Pineapple' } },
    { id: 'mango', emoji: '🥭', label: { ko: '망고', en: 'Mango' } },
    { id: 'kiwi', emoji: '🥝', label: { ko: '키위', en: 'Kiwi' } },
    { id: 'tomato', emoji: '🍅', label: { ko: '토마토', en: 'Tomato' } },
    { id: 'coconut', emoji: '🥥', label: { ko: '코코넛', en: 'Coconut' } },
    { id: 'avocado', emoji: '🥑', label: { ko: '아보카도', en: 'Avocado' } },
    { id: 'eggplant', emoji: '🍆', label: { ko: '가지', en: 'Eggplant' } },
    { id: 'potato', emoji: '🥔', label: { ko: '감자', en: 'Potato' } },
    { id: 'carrot', emoji: '🥕', label: { ko: '당근', en: 'Carrot' } },
    { id: 'corn', emoji: '🌽', label: { ko: '옥수수', en: 'Corn' } },
    { id: 'hotpepper', emoji: '🌶️', label: { ko: '고추', en: 'Chili' } },
    { id: 'cucumber', emoji: '🥒', label: { ko: '오이', en: 'Cucumber' } },
    { id: 'broccoli', emoji: '🥦', label: { ko: '브로콜리', en: 'Broccoli' } },
    { id: 'garlic', emoji: '🧄', label: { ko: '마늘', en: 'Garlic' } },
    { id: 'onion', emoji: '🧅', label: { ko: '양파', en: 'Onion' } },
    { id: 'mushroom', emoji: '🍄', label: { ko: '버섯', en: 'Mushroom' } },
    { id: 'peanuts', emoji: '🥜', label: { ko: '땅콩', en: 'Peanuts' } },
    { id: 'bread', emoji: '🍞', label: { ko: '빵', en: 'Bread' } },
    { id: 'football', emoji: '🏈', label: { ko: '미식축구', en: 'Football' } },
    { id: 'rugby', emoji: '🏉', label: { ko: '럭비', en: 'Rugby' } },
    { id: 'bowling', emoji: '🎳', label: { ko: '볼링', en: 'Bowling' } },
    { id: 'pingpong', emoji: '🏓', label: { ko: '탁구', en: 'Ping pong' } },
    { id: 'badminton', emoji: '🏸', label: { ko: '배드민턴', en: 'Badminton' } },
    { id: 'boxing', emoji: '🥊', label: { ko: '복싱', en: 'Boxing' } },
    { id: 'martial', emoji: '🥋', label: { ko: '태권도', en: 'Martial' } },
    { id: 'golf', emoji: '⛳', label: { ko: '골프', en: 'Golf' } },
    { id: 'fishing', emoji: '🎣', label: { ko: '낚시', en: 'Fishing' } },
    { id: 'diving', emoji: '🤿', label: { ko: '다이빙', en: 'Diving' } },
    { id: 'skis', emoji: '🎿', label: { ko: '스키', en: 'Skis' } },
    { id: 'sled', emoji: '🛷', label: { ko: '썰매', en: 'Sled' } },
    { id: 'dart', emoji: '🎯', label: { ko: '과녁', en: 'Dart' } },
    { id: 'kite', emoji: '🪁', label: { ko: '연', en: 'Kite' } },
    { id: 'eightball', emoji: '🎱', label: { ko: '당구', en: '8 ball' } },
    { id: 'crystal', emoji: '🔮', label: { ko: '수정구', en: 'Crystal' } },
    { id: 'joystick', emoji: '🕹️', label: { ko: '조이스틱', en: 'Joystick' } },
    { id: 'slot', emoji: '🎰', label: { ko: '슬롯', en: 'Slot' } },
    { id: 'puzzle', emoji: '🧩', label: { ko: '퍼즐', en: 'Puzzle' } },
    { id: 'teddy', emoji: '🧸', label: { ko: '테디', en: 'Teddy' } },
    { id: 'chess', emoji: '♟️', label: { ko: '체스', en: 'Chess' } },
    { id: 'joker', emoji: '🃏', label: { ko: '조커', en: 'Joker' } },
    { id: 'mahjong', emoji: '🀄', label: { ko: '마작', en: 'Mahjong' } },
    { id: 'ambulance', emoji: '🚑', label: { ko: '구급차', en: 'Ambulance' } },
    { id: 'firetruck', emoji: '🚒', label: { ko: '소방차', en: 'Fire truck' } },
    { id: 'policecar', emoji: '🚓', label: { ko: '경찰차', en: 'Police car' } },
    { id: 'motorcycle', emoji: '🏍️', label: { ko: '오토바이', en: 'Motorcycle' } },
    { id: 'scooter', emoji: '🛵', label: { ko: '스쿠터', en: 'Scooter' } },
    { id: 'skateboard', emoji: '🛹', label: { ko: '스케이트보드', en: 'Skateboard' } },
    { id: 'truck', emoji: '🚚', label: { ko: '트럭', en: 'Truck' } },
    { id: 'tractor', emoji: '🚜', label: { ko: '트랙터', en: 'Tractor' } },
    { id: 'racecar', emoji: '🏎️', label: { ko: '레이싱', en: 'Race car' } },
    { id: 'helicopter', emoji: '🚁', label: { ko: '헬기', en: 'Helicopter' } },
    { id: 'ufo', emoji: '🛸', label: { ko: '유에프오', en: 'UFO' } },
    { id: 'canoe', emoji: '🛶', label: { ko: '카누', en: 'Canoe' } },
    { id: 'speedboat', emoji: '🚤', label: { ko: '보트', en: 'Boat' } },
    { id: 'anchor', emoji: '⚓', label: { ko: '닻', en: 'Anchor' } },
    { id: 'fuel', emoji: '⛽', label: { ko: '주유', en: 'Fuel' } },
    { id: 'traffic', emoji: '🚦', label: { ko: '신호등', en: 'Traffic' } },
    { id: 'cone', emoji: '🚧', label: { ko: '공사중', en: 'Cone' } },
    { id: 'map', emoji: '🗺️', label: { ko: '지도', en: 'Map' } },
    { id: 'compass', emoji: '🧭', label: { ko: '나침반', en: 'Compass' } },
    { id: 'mountain', emoji: '⛰️', label: { ko: '산', en: 'Mountain' } },
    { id: 'volcano', emoji: '🌋', label: { ko: '화산', en: 'Volcano' } },
    { id: 'camping', emoji: '🏕️', label: { ko: '캠핑', en: 'Camping' } },
    { id: 'beach', emoji: '🏖️', label: { ko: '해변', en: 'Beach' } },
    { id: 'island', emoji: '🏝️', label: { ko: '섬', en: 'Island' } },
    { id: 'park', emoji: '🏞️', label: { ko: '공원', en: 'Park' } },
    { id: 'stadium', emoji: '🏟️', label: { ko: '경기장', en: 'Stadium' } },
    { id: 'castle', emoji: '🏰', label: { ko: '성', en: 'Castle' } },
    { id: 'tokyo', emoji: '🗼', label: { ko: '타워', en: 'Tower' } },
    { id: 'liberty', emoji: '🗽', label: { ko: '자유여신', en: 'Liberty' } },
    { id: 'fountain', emoji: '⛲', label: { ko: '분수', en: 'Fountain' } },
    { id: 'tent', emoji: '⛺', label: { ko: '텐트', en: 'Tent' } },
    { id: 'cityscape', emoji: '🌆', label: { ko: '도시', en: 'City' } },
    { id: 'metro', emoji: '🚇', label: { ko: '지하철', en: 'Metro' } },
    { id: 'station', emoji: '🚉', label: { ko: '역', en: 'Station' } },
    { id: 'busstop', emoji: '🚏', label: { ko: '정류장', en: 'Bus stop' } },
    { id: 'newmoon', emoji: '🌑', label: { ko: '삭', en: 'New moon' } },
    { id: 'stars', emoji: '🌠', label: { ko: '별똥별', en: 'Shooting star' } },
    { id: 'galaxy', emoji: '🌌', label: { ko: '은하수', en: 'Galaxy' } },
    { id: 'fog', emoji: '🌫️', label: { ko: '안개', en: 'Fog' } },
    { id: 'wind', emoji: '🌬️', label: { ko: '바람', en: 'Wind' } },
    { id: 'tornado', emoji: '🌪️', label: { ko: '토네이도', en: 'Tornado' } },
    { id: 'cyclone', emoji: '🌀', label: { ko: '태풍', en: 'Cyclone' } },
    { id: 'seedling', emoji: '🌱', label: { ko: '새싹', en: 'Seedling' } },
    { id: 'potted', emoji: '🪴', label: { ko: '화분', en: 'Potted' } },
    { id: 'cactus', emoji: '🌵', label: { ko: '선인장', en: 'Cactus' } },
    { id: 'herb', emoji: '🌿', label: { ko: '풀', en: 'Herb' } },
    { id: 'maple', emoji: '🍁', label: { ko: '단풍', en: 'Maple' } },
    { id: 'leaves', emoji: '🍃', label: { ko: '나뭇잎', en: 'Leaves' } },
    { id: 'hibiscus', emoji: '🌺', label: { ko: '무궁화', en: 'Hibiscus' } },
    { id: 'blossom', emoji: '🌼', label: { ko: '꽃', en: 'Blossom' } },
    { id: 'wilted', emoji: '🥀', label: { ko: '시든꽃', en: 'Wilted' } },
    { id: 'lotus', emoji: '🪷', label: { ko: '연꽃', en: 'Lotus' } },
    { id: 'watch', emoji: '⌚', label: { ko: '시계', en: 'Watch' } },
    { id: 'flashlight', emoji: '🔦', label: { ko: '손전등', en: 'Flashlight' } },
    { id: 'candle', emoji: '🕯️', label: { ko: '촛불', en: 'Candle' } },
    { id: 'openbook', emoji: '📖', label: { ko: '펼친책', en: 'Open book' } },
    { id: 'newspaper', emoji: '📰', label: { ko: '신문', en: 'News' } },
    { id: 'bookmark', emoji: '🔖', label: { ko: '책갈피', en: 'Bookmark' } },
    { id: 'yen', emoji: '💴', label: { ko: '엔', en: 'Yen' } },
    { id: 'credit', emoji: '💳', label: { ko: '카드', en: 'Card' } },
    { id: 'receipt', emoji: '🧾', label: { ko: '영수증', en: 'Receipt' } },
    { id: 'chart', emoji: '📊', label: { ko: '그래프', en: 'Chart' } },
    { id: 'pencil', emoji: '✏️', label: { ko: '연필', en: 'Pencil' } },
    { id: 'pen', emoji: '🖊️', label: { ko: '펜', en: 'Pen' } },
    { id: 'paintbrush', emoji: '🖌️', label: { ko: '붓', en: 'Brush' } },
    { id: 'crayon', emoji: '🖍️', label: { ko: '크레용', en: 'Crayon' } },
    { id: 'briefcase', emoji: '💼', label: { ko: '서류가방', en: 'Briefcase' } },
    { id: 'folder', emoji: '📁', label: { ko: '폴더', en: 'Folder' } },
    { id: 'calendar', emoji: '📅', label: { ko: '달력', en: 'Calendar' } },
    { id: 'clipboard', emoji: '📋', label: { ko: '클립보드', en: 'Clipboard' } },
    { id: 'paperclip', emoji: '📎', label: { ko: '클립', en: 'Clip' } },
    { id: 'ruler', emoji: '📏', label: { ko: '자', en: 'Ruler' } },
    { id: 'scissors', emoji: '✂️', label: { ko: '가위', en: 'Scissors' } },
    { id: 'trash', emoji: '🗑️', label: { ko: '휴지통', en: 'Trash' } },
    { id: 'unlock', emoji: '🔓', label: { ko: '열림', en: 'Unlock' } },
    { id: 'battery', emoji: '🔋', label: { ko: '배터리', en: 'Battery' } },
    { id: 'plug', emoji: '🔌', label: { ko: '플러그', en: 'Plug' } },
    { id: 'desktop', emoji: '🖥️', label: { ko: '데스크톱', en: 'Desktop' } },
    { id: 'printer', emoji: '🖨️', label: { ko: '프린터', en: 'Printer' } },
    { id: 'cd', emoji: '💿', label: { ko: '시디', en: 'CD' } },
    { id: 'radio', emoji: '📻', label: { ko: '라디오', en: 'Radio' } },
    { id: 'violin', emoji: '🎻', label: { ko: '바이올린', en: 'Violin' } },
    { id: 'drum', emoji: '🥁', label: { ko: '드럼', en: 'Drum' } },
    { id: 'sax', emoji: '🎷', label: { ko: '색소폰', en: 'Sax' } },
    { id: 'trumpet', emoji: '🎺', label: { ko: '트럼펫', en: 'Trumpet' } },
    { id: 'piano', emoji: '🎹', label: { ko: '피아노', en: 'Piano' } },
    { id: 'redcircle', emoji: '🔴', label: { ko: '빨간원', en: 'Red circle' } },
    { id: 'orangecircle', emoji: '🟠', label: { ko: '주황원', en: 'Orange circle' } },
    { id: 'yellowcircle', emoji: '🟡', label: { ko: '노란원', en: 'Yellow circle' } },
    { id: 'greencircle', emoji: '🟢', label: { ko: '초록원', en: 'Green circle' } },
    { id: 'bluecircle', emoji: '🔵', label: { ko: '파란원', en: 'Blue circle' } },
    { id: 'purplecircle', emoji: '🟣', label: { ko: '보라원', en: 'Purple circle' } },
    { id: 'blackcircle', emoji: '⚫', label: { ko: '검은원', en: 'Black circle' } },
    { id: 'whitecircle', emoji: '⚪', label: { ko: '흰원', en: 'White circle' } },
    { id: 'redsquare', emoji: '🟥', label: { ko: '빨간네모', en: 'Red square' } },
    { id: 'bluesquare', emoji: '🟦', label: { ko: '파란네모', en: 'Blue square' } },
    { id: 'plus', emoji: '➕', label: { ko: '더하기', en: 'Plus' } },
    { id: 'minus', emoji: '➖', label: { ko: '빼기', en: 'Minus' } },
    { id: 'divide', emoji: '➗', label: { ko: '나누기', en: 'Divide' } },
    { id: 'arrowup', emoji: '⬆️', label: { ko: '위화살', en: 'Up' } },
    { id: 'arrowdown', emoji: '⬇️', label: { ko: '아래화살', en: 'Down' } },
    { id: 'arrowleft', emoji: '⬅️', label: { ko: '왼화살', en: 'Left' } },
    { id: 'arrowright', emoji: '➡️', label: { ko: '오른화살', en: 'Right' } },
    { id: 'refresh', emoji: '🔄', label: { ko: '새로고침', en: 'Refresh' } },
    { id: 'play', emoji: '▶️', label: { ko: '재생', en: 'Play' } },
    { id: 'pause', emoji: '⏸️', label: { ko: '일시정지', en: 'Pause' } },
    { id: 'repeat', emoji: '🔁', label: { ko: '반복', en: 'Repeat' } },
    { id: 'bright', emoji: '🔆', label: { ko: '밝음', en: 'Bright' } },
    { id: 'signal', emoji: '📶', label: { ko: '신호', en: 'Signal' } },
    { id: 'mute', emoji: '🔇', label: { ko: '음소거', en: 'Mute' } },
    { id: 'speaker', emoji: '🔊', label: { ko: '스피커', en: 'Speaker' } },
    { id: 'jp', emoji: '🇯🇵', label: { ko: '일본', en: 'Japan' } },
    { id: 'us', emoji: '🇺🇸', label: { ko: '미국', en: 'USA' } },
    { id: 'cn', emoji: '🇨🇳', label: { ko: '중국', en: 'China' } },
    { id: 'gb', emoji: '🇬🇧', label: { ko: '영국', en: 'UK' } },
    { id: 'fr', emoji: '🇫🇷', label: { ko: '프랑스', en: 'France' } },
    { id: 'de', emoji: '🇩🇪', label: { ko: '독일', en: 'Germany' } },
    { id: 'shaking', emoji: '🫨', label: { ko: '흔들림', en: 'Shaking' } },
    { id: 'bubbles', emoji: '🫧', label: { ko: '거품', en: 'Bubbles' } },
    { id: 'mirror', emoji: '🪞', label: { ko: '거울', en: 'Mirror' } },
    { id: 'window', emoji: '🪟', label: { ko: '창문', en: 'Window' } },
    { id: 'chair', emoji: '🪑', label: { ko: '의자', en: 'Chair' } },
    { id: 'mousecomp', emoji: '🖱️', label: { ko: '마우스', en: 'Mouse' } },
    { id: 'abacus', emoji: '🧮', label: { ko: '주판', en: 'Abacus' } },
    { id: 'ladder', emoji: '🪜', label: { ko: '사다리', en: 'Ladder' } },
    { id: 'toolbox', emoji: '🧰', label: { ko: '공구함', en: 'Toolbox' } },
    { id: 'screwdriver', emoji: '🪛', label: { ko: '드라이버', en: 'Screwdriver' } },
    { id: 'wrench', emoji: '🔧', label: { ko: '렌치', en: 'Wrench' } },
    { id: 'hammer', emoji: '🔨', label: { ko: '망치', en: 'Hammer' } },
    { id: 'axe', emoji: '🪓', label: { ko: '도끼', en: 'Axe' } },
    { id: 'gear', emoji: '⚙️', label: { ko: '톱니', en: 'Gear' } },
    { id: 'brick', emoji: '🧱', label: { ko: '벽돌', en: 'Brick' } },
    { id: 'magnet', emoji: '🧲', label: { ko: '자석', en: 'Magnet' } },
    { id: 'testtube', emoji: '🧪', label: { ko: '시험관', en: 'Test tube' } },
    { id: 'dna', emoji: '🧬', label: { ko: '디엔에이', en: 'DNA' } },
    { id: 'telescope', emoji: '🔭', label: { ko: '망원경', en: 'Telescope' } },
    { id: 'microscope', emoji: '🔬', label: { ko: '현미경', en: 'Microscope' } },
    { id: 'satellite', emoji: '📡', label: { ko: '안테나', en: 'Satellite' } },
    { id: 'syringe', emoji: '💉', label: { ko: '주사기', en: 'Syringe' } },
    { id: 'pill', emoji: '💊', label: { ko: '약', en: 'Pill' } },
    { id: 'stethoscope', emoji: '🩺', label: { ko: '청진기', en: 'Stethoscope' } },
    { id: 'xray', emoji: '🩻', label: { ko: '엑스레이', en: 'X-ray' } },
    { id: 'crutch', emoji: '🩼', label: { ko: '목발', en: 'Crutch' } },
    { id: 'wheelchair', emoji: '♿', label: { ko: '휠체어', en: 'Wheelchair' } },
    { id: 'cane', emoji: '🦯', label: { ko: '지팡이', en: 'Cane' } },
    { id: 'soap', emoji: '🧼', label: { ko: '비누', en: 'Soap' } },
    { id: 'toothbrush', emoji: '🪥', label: { ko: '칫솔', en: 'Toothbrush' } },
    { id: 'sponge', emoji: '🧽', label: { ko: '스펀지', en: 'Sponge' } },
    { id: 'lotion', emoji: '🧴', label: { ko: '로션', en: 'Lotion' } },
    { id: 'safetyvest', emoji: '🦺', label: { ko: '조끼', en: 'Vest' } },
    { id: 'goggles', emoji: '🥽', label: { ko: '고글', en: 'Goggles' } },
    { id: 'labcoat', emoji: '🥼', label: { ko: '실험복', en: 'Lab coat' } },
    { id: 'coat', emoji: '🧥', label: { ko: '코트', en: 'Coat' } },
    { id: 'jeans', emoji: '👖', label: { ko: '청바지', en: 'Jeans' } },
    { id: 'scarf', emoji: '🧣', label: { ko: '목도리', en: 'Scarf' } },
    { id: 'gloves', emoji: '🧤', label: { ko: '장갑', en: 'Gloves' } },
    { id: 'socks', emoji: '🧦', label: { ko: '양말', en: 'Socks' } },
    { id: 'shorts', emoji: '🩳', label: { ko: '반바지', en: 'Shorts' } },
    { id: 'bikini', emoji: '👙', label: { ko: '비키니', en: 'Bikini' } },
    { id: 'onepiece', emoji: '🩱', label: { ko: '수영복', en: 'Swim' } },
    { id: 'kimono', emoji: '👘', label: { ko: '기모노', en: 'Kimono' } },
    { id: 'billedcap', emoji: '🧢', label: { ko: '모자', en: 'Cap' } },
    { id: 'tophat', emoji: '🎩', label: { ko: '실크햇', en: 'Top hat' } },
    { id: 'graduation', emoji: '🎓', label: { ko: '학사모', en: 'Grad' } },
    { id: 'mutebell', emoji: '🔕', label: { ko: '알림끄기', en: 'Bell off' } },
    { id: 'loudspeaker', emoji: '📣', label: { ko: '메가폰', en: 'Horn' } },
    { id: 'inbox', emoji: '📥', label: { ko: '수신함', en: 'Inbox' } },
    { id: 'outbox', emoji: '📤', label: { ko: '발신함', en: 'Outbox' } },
    { id: 'package', emoji: '📦', label: { ko: '택배', en: 'Package' } },
    { id: 'mailbox', emoji: '📫', label: { ko: '우편함', en: 'Mailbox' } },
    { id: 'scroll', emoji: '📜', label: { ko: '두루마리', en: 'Scroll' } },
    { id: 'page', emoji: '📄', label: { ko: '문서', en: 'Page' } },
    { id: 'notebook', emoji: '📓', label: { ko: '노트', en: 'Notebook' } },
    { id: 'orangebook', emoji: '📙', label: { ko: '주황책', en: 'Orange book' } },
    { id: 'bluebook', emoji: '📘', label: { ko: '파란책', en: 'Blue book' } },
    { id: 'greenbook', emoji: '📗', label: { ko: '초록책', en: 'Green book' } },
    { id: 'redbook', emoji: '📕', label: { ko: '빨간책', en: 'Red book' } },
    { id: 'label', emoji: '🏷️', label: { ko: '라벨', en: 'Label' } },
    { id: 'moneywings', emoji: '💸', label: { ko: '날돈', en: 'Money fly' } },
    { id: 'coin', emoji: '🪙', label: { ko: '동전', en: 'Coin' } },
    { id: 'whiteflag', emoji: '🏳️', label: { ko: '흰깃발', en: 'White flag' } },
    { id: 'blackflag', emoji: '🏴', label: { ko: '검은깃발', en: 'Black flag' } },
    { id: 'pirate', emoji: '🏴‍☠️', label: { ko: '해적', en: 'Pirate' } },
    { id: 'rainbowflag', emoji: '🏳️‍🌈', label: { ko: '무지개깃발', en: 'Pride' } },
    { id: 'checkered', emoji: '🏁', label: { ko: '결승', en: 'Finish' } },
    { id: 'triangular', emoji: '🚩', label: { ko: '삼각깃발', en: 'Flag' } },
    { id: 'crossedflags', emoji: '🎌', label: { ko: '교차깃발', en: 'Crossed flags' } },
    { id: 'bandage', emoji: '🩹', label: { ko: '밴드', en: 'Bandage' } },
    { id: 'blood', emoji: '🩸', label: { ko: '피', en: 'Blood' } },
    { id: 'plunger', emoji: '🪠', label: { ko: '뚫어뻥', en: 'Plunger' } },
    { id: 'pickaxe', emoji: '⛏️', label: { ko: '곡괭이', en: 'Pick' } },
    { id: 'petri', emoji: '🧫', label: { ko: '페트리', en: 'Petri' } },
    { id: 'rescuehelm', emoji: '⛑️', label: { ko: '구조헬멧', en: 'Rescue' } },
    { id: 'armyhelm', emoji: '🪖', label: { ko: '군모', en: 'Army helm' } },
    { id: 'prayerbeads', emoji: '📿', label: { ko: '염주', en: 'Beads' } },
];

export const STICKER_MOTIONS = ['bob', 'pulse', 'wiggle', 'shake', 'pop'] as const;

export type StickerMotion = (typeof STICKER_MOTIONS)[number];

export const SIMPLE_STICKER_IDS: readonly string[] = [
    'love', 'heart', 'like', 'dislike', 'ok', 'grin', 'lol', 'rofl', 'wink', 'cool',
    'think', 'wow', 'scream', 'sad', 'cry', 'angry', 'sleepy', 'kiss', 'blush', 'thanks',
    'clap', 'wave', 'party', 'fire', 'star', 'check', 'eyes', 'hug', 'pleading', 'partying',
    'cat', 'dog', 'sun', 'moon', 'hundred', 'sparkle', 'idea', 'poop', 'ghost', 'flex',
    'peace', 'okhand', 'explode', 'zany', 'rolling', 'sweat', 'best', 'gift',
];

export function stickerById(id: string): Sticker | undefined {
    return STICKERS.find((item) => item.id === id);
}

export function stickersForPack(pack: string): Sticker[] {
    if (pack === 'simple') {
        return SIMPLE_STICKER_IDS
            .map((id) => stickerById(id))
            .filter((item): item is Sticker => Boolean(item));
    }
    return STICKERS;
}

export function stickerMotion(id: string): StickerMotion {
    let sum = 0;
    for (let index = 0; index < id.length; index += 1) {
        sum += id.charCodeAt(index);
    }
    return STICKER_MOTIONS[sum % STICKER_MOTIONS.length] ?? 'bob';
}

export function stickerToken(id: string): string {
    return `[[s:${id}]]`;
}

export function imageToken(id: number): string {
    return `[[i:${id}]]`;
}
